// הצד של ChatGPT ב-AI Council, אוטומטי: פעם ביום קורא את Issue #25 ואת נתוני הפלטפורמה, מבקש מ-ChatGPT (OpenAI API)
// סקירה של מהנדס שני לפי כללי AI_COUNCIL.md, ומפרסם אותה כתגובה בשם **ChatGPT**. ריצת ה-Routine של Claude עונה בערב.
// בלי מפתח (OPENAI_API_KEY) — לא עושה כלום. שימוש: OPENAI_API_KEY=... GH_TOKEN=... WORKER_URL=... node invest-api/scripts/council-chatgpt.mjs
import { readFileSync } from 'node:fs';

export const REPO = process.env.REPO || 'meirco199-prog/bikur';
export const ISSUE = Number(process.env.ISSUE || 25);
export const MARKER = 'council-chatgpt';
const MAX_COMMENTS = 20, MAX_COMMENT_CHARS = 3000, MAX_DATA_CHARS = 5000, MAX_OUT_TOKENS = 1800;

export const todayIso = () => new Date().toISOString().slice(0, 10);
export const kindOf = (c) => { const b = String(c.body || ''); const bot = /\[bot\]$/.test(c.user?.login || ''); if (bot && b.startsWith('**ChatGPT**')) return 'ChatGPT'; if (bot && b.startsWith('<!-- health-report')) return 'דוח תקינות (אוטומטי)'; if (bot) return 'bot'; return b.includes('_Generated by [Claude Code]') ? 'Claude' : `בעל הריפו (${c.user?.login || ''})`; };
// לא לרוץ פעמיים באותו יום, ולא כשאין שום תגובה חדשה מאז הסקירה האוטומטית הקודמת
export function shouldSkip(comments, today = todayIso()){
  const idx = comments.map((c) => String(c.body || '')).reduce((last, b, i) => (b.includes(`<!-- ${MARKER} `) ? i : last), -1);
  if (idx >= 0 && String(comments[idx].body).includes(`<!-- ${MARKER} ${today} -->`)) return 'כבר פורסמה סקירה היום';
  if (idx >= 0 && idx === comments.length - 1) return 'אין תגובה חדשה מאז הסקירה הקודמת';
  return null;
}
export function buildMessages({ comments, data, rules, today = todayIso() }){
  const system = [
    'אתה ChatGPT, המהנדס השני (לצד Claude) ב-AI Council של פלטפורמת ההשקעות בריפו meirco199-prog/bikur (חשבון תרגול, לא כסף אמיתי). בעל הריפו (מאיר) מכריע; הוא לא משתתף בדיון השוטף ומצפה ששני המהנדסים ינהלו אותו לבד.',
    'זו ריצה אוטומטית יומית. הפלט שלך מתפרסם כמו שהוא כתגובה ב-Issue #25, ו-Claude קורא ועונה בערב (ריצה מתוזמנת), ומתקן באגים מוכחים ב-PR.',
    '', '## כללי העבודה (מ-AI_COUNCIL.md, מחייבים):', rules,
    '', '## מה לכתוב:',
    '- עברית, Markdown, עד 2500 תווים. פנה ל-Claude ישירות: מה לבדוק, איפה (קובץ/נתיב/ריצה), ומה תוצאה תקינה.',
    '- קרא קודם את התשובות של Claude לממצאים הקודמים שלך. אל תחזור על ממצא שכבר נענה, אלא אם התשובה לא מספקת — ואז אמור בדיוק למה.',
    '- לכל ממצא: **קטגוריה** (באג מוכח / סיכון אפשרי / החלטת ארכיטקטורה / השערת אסטרטגיה / שינוי מבוסס-נתונים), **Issue**, **ChatGPT position**, **Evidence from code/data** (מספרים מהנתונים שקיבלת), **Proposed experiment/fix**, **What would change ChatGPT\'s mind**.',
    '- תקופת ניסוי קפואה: אין להציע שינוי משקלים/ספים/אסטרטגיה כתיקון. השערת אסטרטגיה — רק כניסוי Shadow/A-B, והכרעה אצל מאיר.',
    '- דברים שרק מאיר מחליט (כסף, מנויים, מינוף, אסטרטגיה): ציין "ממתין להחלטת מאיר" ואל תבקש מ-Claude לבצע.',
    '- אסור לכלול מפתחות, טוקנים או סודות, גם לא כדוגמה.',
    '- אם אחרי בדיקה אין לך ממצא חדש: כתוב שורה אחת "אין ממצאים חדשים היום" ושורה אחת מה בדקת. אל תמציא ממצא כדי למלא מקום.',
  ].join('\n');
  const thread = comments.slice(-MAX_COMMENTS).map((c) => `### ${String(c.created_at || '').slice(0, 16).replace('T', ' ')} · ${kindOf(c)}\n${String(c.body || '').slice(0, MAX_COMMENT_CHARS)}${String(c.body || '').length > MAX_COMMENT_CHARS ? '\n…(קוצר)' : ''}`).join('\n\n');
  const dataTxt = Object.entries(data).map(([k, v]) => { const s = typeof v === 'string' ? v : JSON.stringify(v); return `### ${k}\n${s.slice(0, MAX_DATA_CHARS)}${s.length > MAX_DATA_CHARS ? '…(קוצר)' : ''}`; }).join('\n\n');
  const user = `היום ${today}.\n\n## Issue #25 — ${comments.length} תגובות, ${Math.min(MAX_COMMENTS, comments.length)} האחרונות (מהישנה לחדשה):\n\n${thread}\n\n## נתונים חיים מה-Worker (GET ציבורי):\n\n${dataTxt}\n\nכתוב את הסקירה היומית שלך.`;
  return [{ role: 'system', content: system }, { role: 'user', content: user }];
}
export const redact = (s) => String(s).replace(/\b(sk-[A-Za-z0-9_-]{8,}|ghp_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,})\b/g, '[REDACTED]');
export function formatComment({ text, model, runUrl, today = todayIso() }){
  return `**ChatGPT** (סקירה אוטומטית יומית של המהנדס השני, ${model}, דרך OpenAI API — לא ישירות מהחשבון):\n<!-- ${MARKER} ${today} -->\n\n${redact(text).trim()}\n\n---\n_Posted by council-chatgpt.yml${runUrl ? ` · [ריצה](${runUrl})` : ''}_`;
}

const isMain = process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop());
if (isMain){
  const KEY = process.env.OPENAI_API_KEY, GH = process.env.GH_TOKEN, W = (process.env.WORKER_URL || '').replace(/\/$/, '');
  const MODEL = process.env.OPENAI_MODEL || 'gpt-5';
  if (!KEY){ console.log('::notice::OPENAI_API_KEY לא מוגדר — הצד האוטומטי של ChatGPT כבוי (זה מצב תקין עד שבעל הריפו מאשר)'); process.exit(0); }
  if (!GH || !W){ console.error('חסר GH_TOKEN או WORKER_URL'); process.exit(1); }
  const ghHdr = { Authorization: `Bearer ${GH}`, Accept: 'application/vnd.github+json', 'User-Agent': 'bikur-council-chatgpt', 'X-GitHub-Api-Version': '2022-11-28' };
  const comments = await (await fetch(`https://api.github.com/repos/${REPO}/issues/${ISSUE}/comments?per_page=100`, { headers: ghHdr })).json();
  if (!Array.isArray(comments)){ console.error('GitHub לא החזיר תגובות:', JSON.stringify(comments).slice(0, 200)); process.exit(1); }
  const skip = shouldSkip(comments); if (skip){ console.log(`מדלג: ${skip}`); process.exit(0); }
  const get = async (p) => { try { const r = await fetch(`${W}/${p}`); const t = await r.text(); try { return JSON.parse(t); } catch { return `HTTP ${r.status}`; } } catch (e) { return `error: ${e.message}`; } };
  const [health, cron, rank, shadow, paper, aggr] = await Promise.all([get('health'), get('cron/status'), get('rank'), get('shadow/report'), get('paper'), get('aggressive/report')]);
  const data = { health, 'cron/status': cron, rank, 'shadow/report': shadow, paper, 'aggressive/report': aggr };
  let rules = ''; try { rules = readFileSync(new URL('../../AI_COUNCIL.md', import.meta.url), 'utf8').split('\n## יומן הנושאים')[0].slice(0, 9000); } catch { rules = '(AI_COUNCIL.md לא נמצא — פעל לפי הכללים שבהודעה זו)'; }
  const messages = buildMessages({ comments, data, rules });
  const r = await fetch('https://api.openai.com/v1/chat/completions', { method: 'POST', headers: { Authorization: `Bearer ${KEY}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: MODEL, messages, max_completion_tokens: MAX_OUT_TOKENS }) });
  const j = await r.json().catch(() => ({}));
  if (!r.ok){ console.error(`OpenAI ${r.status}: ${redact(JSON.stringify(j.error || j).slice(0, 300))}`); process.exit(1); }
  const text = j.choices?.[0]?.message?.content || '';
  if (!text.trim()){ console.error('תשובה ריקה מ-OpenAI'); process.exit(1); }
  console.log(`usage: ${JSON.stringify(j.usage || {})}`);
  const body = formatComment({ text, model: j.model || MODEL, runUrl: process.env.RUN_URL });
  const post = await fetch(`https://api.github.com/repos/${REPO}/issues/${ISSUE}/comments`, { method: 'POST', headers: { ...ghHdr, 'Content-Type': 'application/json' }, body: JSON.stringify({ body }) });
  const pj = await post.json().catch(() => ({}));
  if (!post.ok){ console.error(`GitHub ${post.status}: ${String(pj.message || '').slice(0, 200)}`); process.exit(1); }
  console.log(`פורסם: ${pj.html_url}`);
}
