// הסוכן האוטונומי הרב-נכסי — סימולציית חשבון margin בסגנון IBKR: מניות, ETF (גם ממונפים), סחורות, אג"ח, קריפטו, מט"ח, חוזים.
// לונג ושורט, מינוף, עצירות, חיסול margin. הכול סימולציה: אין ברוקר, אין כסף אמיתי. מודל שפה לא שולח פקודות — אסטרטגיות בקוד ושער פקודות.
import { api, invalidate } from '../core/api.js';
import { esc, fmt, isNum, cls, el, toast } from '../core/util.js';
import { loading, errorBox, disclaimer } from '../ui/components.js';
import { lineChart, barChart } from '../ui/chart.js';

const CLASS_HE = { stock: 'מניות', etf: 'ETF', crypto: 'קריפטו', fx: 'מט"ח', future: 'חוזים', bond: 'אג"ח' };
const SIDE_HE = { long: 'לונג', short: 'שורט', buy: 'קנייה', sell: 'מכירה', cover: 'כיסוי' };
const usd = (v, d = 0) => (isNum(v) ? (v < 0 ? '−' : '') + '$' + fmt.num(Math.abs(v), d) : '—');
const sec = (title, body, tag = '') => `<section class="card" style="margin-bottom:1rem"><div class="row" style="justify-content:space-between;align-items:baseline"><h2 style="margin:0 0 .5rem">${esc(title)}</h2>${tag ? `<span class="tag">${esc(tag)}</span>` : ''}</div>${body}</section>`;
const kpi = (v, l, k = '') => `<div class="kpi"><span class="v ${k}">${v}</span><span class="l">${esc(l)}</span></div>`;
const evidence = (e) => Object.entries(e || {}).filter(([, v]) => v !== null && v !== undefined).map(([k, v]) => `${esc(k)}: ${typeof v === 'number' ? (Math.abs(v) < 1 && k !== 'rank' && k !== 'of' && k !== 'rsi14' ? fmt.pct(v, 1, true) : fmt.num(v, 2)) : esc(v)}`).join(' · ');

function equityChart(rows){
  if (!rows || rows.length < 2) return el(`<div class="muted" style="font-size:.85rem">הגרף יתמלא אחרי כמה ימי מסחר (יש ${rows?.length || 0}).</div>`);
  const series = [{ name: 'הסוכן (₪)', values: rows.map((r) => r[1]), color: '#7c3aed', area: true }];
  const s0 = rows.find((r) => isNum(r[2]))?.[2]; if (s0) series.push({ name: 'SPY (מותאם)', values: rows.map((r) => (isNum(r[2]) ? r[2] / s0 * rows[0][1] : null)), color: '#94a3b8', dashed: true });
  return lineChart({ dates: rows.map((r) => r[0]), series, height: 220, yFmt: (v) => fmt.num(v, 0) });
}

export async function render(main){
  main.innerHTML = loading('טוען את הסוכן…');
  let r;
  try { r = await api('/agent/report', { ttl: 30000 }); } catch (e) { main.innerHTML = errorBox(e); return; }
  const P = r.policy || {};
  const head = `<h1>🤖 הסוכן האוטונומי</h1><div class="muted" style="margin-bottom:.8rem">סימולציית חשבון margin בסגנון IBKR · ${r.universe?.count || 0} מכשירים: ${Object.entries(r.universe?.byClass || {}).map(([k, v]) => `${CLASS_HE[k] || k} ${v}`).join(', ')} · לונג ושורט · מינוף עד פי ${P.leverage?.total || '—'} · ${P.mode === 'simulation' ? 'סימולציה בלבד, לא כסף אמיתי' : esc(P.mode)}</div>`;
  if (r.missing){ main.innerHTML = `<div style="max-width:860px;margin:0 auto">${head}<div class="empty">הסוכן עוד לא רץ. הריצה הראשונה קורית בלילה אחרי סגירת ניו יורק (או בפקודת ops <code>agent-run</code>).</div>${policyCard(P, r.strategies)}</div>`; return; }
  const m = r.metrics || {}; const eq = r.equity || []; const prev = eq[eq.length - 2];
  const status = [r.policy?.killSwitch ? `<span class="tag missing">⛔ kill switch${P.killReason ? ': ' + esc(P.killReason) : ''}</span>` : '', r.halted ? `<span class="tag stale">⏸ עצירה: ${esc(r.halted.join(' · '))}</span>` : '<span class="tag fact">פעיל</span>'].filter(Boolean).join(' ');
  const hero = `<div class="hero"><div class="big">${fmt.ils(r.totalIls)}</div><div class="sub ${cls(r.dayPnlUsd)}">${isNum(r.dayPnlIls) ? `${fmt.ils(r.dayPnlIls)} היום` : ''} · <span class="${cls(r.pnlIls)}">${fmt.ils(r.pnlIls)} (${fmt.pct(r.pnlPct, 1, true)}) מההתחלה</span></div><div class="muted" style="font-size:.85rem">בסגירת ${esc(r.day)} · ${usd(r.equityUsd)} · שער ${fmt.num(r.fx, 2)} ₪/$ · ${status}</div></div>`;
  const kpis = `<div class="grid g3" style="margin:.6rem 0">${kpi(isNum(r.leverage) ? '×' + fmt.num(r.leverage, 2) : '—', 'מינוף (חשיפה ÷ הון)')}${kpi(usd(r.effectiveGrossUsd), 'חשיפה אפקטיבית')}${kpi(r.marginLoanUsd > 0 ? usd(-r.marginLoanUsd) : usd(r.cashUsd), r.marginLoanUsd > 0 ? 'הלוואת margin' : 'מזומן')}${kpi(usd(r.excessLiquidityUsd), 'נזילות עודפת (חיסול מתחת ל-0)', r.excessLiquidityUsd < 0 ? 'neg' : '')}${kpi(usd((r.feesUsd || 0) + (r.interestUsd || 0) + (r.borrowUsd || 0)), 'עמלות + ריבית + השאלה')}${kpi(`${r.trades || 0} <small>(${r.wins || 0}✓ ${r.losses || 0}✗${r.liquidations ? ' · ' + r.liquidations + ' חיסולים' : ''})</small>`, 'עסקאות שנסגרו')}${kpi(isNum(m.excess) ? fmt.pct(m.excess, 1, true) : '—', 'מול SPY באותה תקופה', cls(m.excess))}${kpi(isNum(m.maxDrawdown) ? fmt.pct(m.maxDrawdown, 1) : '—', 'ירידה מקסימלית מהשיא', 'neg')}${kpi(isNum(m.volAnnual) ? fmt.pct(m.volAnnual, 0) : '—', 'תנודתיות שנתית')}</div>`;
  const ex = r.exposure || {};
  const expo = `<div class="grid g2"><div><div class="muted" style="font-size:.85rem">לפי סוג נכס (חשיפה אפקטיבית, $)</div><div id="ch-class"></div></div><div><div class="muted" style="font-size:.85rem">לפי אסטרטגיה</div><div id="ch-strat"></div></div></div><div class="muted" style="font-size:.85rem;margin-top:.4rem">לונג ${usd(ex.longUsd)} · שורט ${usd(ex.shortUsd)} · אסטרטגיות פעילות: ${(r.activeStrategies || []).map((s) => esc(r.strategies?.[s]?.label || s)).join(' · ') || 'אין'}</div>`;
  const pos = (r.positions || []);
  const posTable = pos.length ? `<div style="overflow-x:auto"><table><thead><tr><th>מכשיר</th><th>סוג</th><th>כיוון</th><th class="num">כמות</th><th class="num">כניסה</th><th class="num">מחיר</th><th class="num">רווח/הפסד</th><th class="num">עצירה</th><th>אסטרטגיה</th><th>מאז</th></tr></thead><tbody>${pos.map((p) => `<tr><td><b>${esc(p.nameHe || p.symbol)}</b> <span class="muted">${esc(p.symbol)}</span>${p.leverage && Math.abs(p.leverage) !== 1 ? ` <span class="tag">×${p.leverage}</span>` : ''}</td><td>${esc(CLASS_HE[p.class] || p.class)}</td><td class="${p.side === 'short' ? 'neg' : 'pos'}">${SIDE_HE[p.side]}</td><td class="num">${fmt.num(Math.abs(p.qty), p.class === 'crypto' ? 4 : 0)}${p.units > 1 ? ` <small>×${p.units}</small>` : ''}</td><td class="num">${fmt.num(p.avg, 2)}</td><td class="num">${fmt.num(p.price, 2)}${p.stale ? ' <span class="tag stale">ישן</span>' : ''}</td><td class="num ${cls(p.pnlUsd)}">${usd(p.pnlUsd)} <small>(${fmt.pct(p.pnlPct, 1, true)})</small></td><td class="num">${isNum(p.stop) ? fmt.num(p.stop, 2) : '—'}</td><td>${esc(p.strategy || '')}</td><td>${esc(p.openedDay || '')}</td></tr>`).join('')}</tbody></table></div>` : '<div class="empty">אין פוזיציות פתוחות.</div>';
  const pend = r.pending?.orders || [];
  const pendBlock = pend.length ? `<div class="muted" style="font-size:.85rem;margin-bottom:.4rem">הוחלטו בסגירת ${esc(r.pending.day)} · יבוצעו בפתיחת הסשן הבא במחיר הפתיחה (בלי look-ahead)</div><table><thead><tr><th>פעולה</th><th>מכשיר</th><th class="num">כמות</th><th class="num">מחיר החלטה</th><th class="num">עצירה</th><th>אסטרטגיה</th><th class="num">ציון</th></tr></thead><tbody>${pend.map((o) => `<tr><td class="${o.side === 'short' ? 'neg' : 'pos'}">${o.side === 'short' ? 'שורט' : 'קנייה'}</td><td><b>${esc(o.symbol)}</b></td><td class="num">${fmt.num(o.qty, 4)}</td><td class="num">${fmt.num(o.price, 2)}</td><td class="num">${fmt.num(o.stop, 2)}</td><td>${esc(r.strategies?.[o.strategy]?.label || o.strategy)}</td><td class="num">${fmt.num(o.score, 0)}</td></tr>`).join('')}</tbody></table>` : '<div class="empty">אין פקודות ממתינות למחר.</div>';
  const O = r.opportunities || {};
  const cands = (O.candidates || []).filter((c) => !c.needsResearch).slice(0, 15), research = (O.candidates || []).filter((c) => c.needsResearch).slice(0, 8);
  const oppBlock = `<div class="muted" style="font-size:.85rem;margin-bottom:.4rem">נסרקו ${O.scanned || 0} מכשירים בסגירת ${esc(O.day || r.day)} · לונג ${O.summary?.long ?? 0} · שורט ${O.summary?.short ?? 0} · למחקר ${O.summary?.research ?? 0}${O.regime ? ' · משטר: ' + esc(O.regime) : ''}</div>${cands.length ? `<div class="stack">${cands.map((c) => `<div class="row" style="justify-content:space-between;gap:.6rem;border-bottom:1px solid var(--line);padding:.35rem 0"><div><b>${esc(c.nameHe || c.symbol)}</b> <span class="muted">${esc(c.symbol)} · ${esc(CLASS_HE[c.class] || c.class)}</span><div class="muted" style="font-size:.82rem">${esc(r.strategies?.[c.strategy]?.label || c.strategy)} · ${evidence(c.evidence)}</div><div class="muted" style="font-size:.8rem">מבטל: ${esc(c.invalidation || '')}${c.conflict ? ' · סתירה: ' + esc(c.conflict) : ''}</div></div><div style="text-align:left;white-space:nowrap"><span class="${c.side === 'short' ? 'neg' : 'pos'}"><b>${SIDE_HE[c.side]}</b></span><br><small>ציון ${fmt.num(c.score, 0)} · עצירה ${fmt.pct(c.stopPct, 1)}</small></div></div>`).join('')}</div>` : '<div class="empty">אין מועמדים לפקודה היום.</div>'}${research.length ? `<details style="margin-top:.6rem"><summary class="muted">זעזועים שדורשים מחקר לפני פקודה (${research.length})</summary>${research.map((c) => `<div class="muted" style="font-size:.85rem;padding:.25rem 0">${esc(c.symbol)}: ${evidence(c.evidence)}</div>`).join('')}</details>` : ''}`;
  const rej = O.gateLog || [];
  const rejBlock = rej.length ? `<details><summary class="muted">${rej.length} מועמדים נדחו בשער הפקודות — למה</summary><div class="stack" style="margin-top:.4rem">${rej.slice(0, 25).map((g) => `<div class="muted" style="font-size:.85rem"><b>${esc(g.symbol)}</b> ${SIDE_HE[g.side] || esc(g.side)} (${esc(g.strategy)}): ${(g.reasons || []).map(esc).join(' · ')}</div>`).join('')}</div></details>` : '<div class="muted" style="font-size:.85rem">כל המועמדים עברו את השער.</div>';
  const J = r.journal || [];
  const jBlock = J.length ? `<div class="stack">${J.slice(0, 25).map((j) => `<div class="muted" style="font-size:.85rem;border-bottom:1px solid var(--line);padding:.3rem 0"><b>${esc(j.day)}</b> · ${j.kind === 'day' ? `סיכום יום: הון ${usd(j.equityUsd)} · ${usd(j.dayPnlUsd)} · מינוף ×${fmt.num(j.leverage, 2)} · ${j.fills} מילויים · ${j.stops} עצירות${j.liquidations ? ' · ' + j.liquidations + ' חיסולים' : ''} · ${j.ordersForTomorrow} פקודות למחר${j.halted ? ' · עצירה: ' + esc(j.halted.join(', ')) : ''}` : j.kind === 'reject' ? `❌ נדחה ${esc(j.symbol)} ${SIDE_HE[j.side] || ''}: ${(j.reasons || []).map(esc).join(' · ')}` : `${j.kind === 'liquidation' ? '⚠️ חיסול' : j.kind === 'stop' ? '🛑 עצירה' : '✅ מילוי'} ${SIDE_HE[j.side] || esc(j.side)} ${fmt.num(j.qty, 4)} ${esc(j.symbol)} @ ${fmt.num(j.price, 2)}${isNum(j.realizedUsd) && j.realizedUsd !== 0 ? ` · ממומש ${usd(j.realizedUsd)}` : ''}${j.reason ? ' · ' + esc(j.reason) : ''}`}</div>`).join('')}</div>` : '<div class="empty">אין רישומים.</div>';
  main.innerHTML = `<div style="max-width:960px;margin:0 auto">${head}
    ${sec('החשבון', hero + kpis + '<div id="ch-eq" style="margin-top:.6rem"></div>', 'סימולציה')}
    ${sec('חשיפות', expo)}
    ${sec('פוזיציות פתוחות', posTable, `${pos.length}`)}
    ${sec('פקודות למחר', pendBlock, `${pend.length}`)}
    ${sec('הזדמנויות שהמנוע מצא', oppBlock, 'סריקה יומית')}
    ${sec('שער הפקודות', rejBlock + `<div class="muted" style="font-size:.85rem;margin-top:.5rem">כל פקודה עוברת בדיקה דטרמיניסטית מול המדיניות: מינוף, חשיפות, הפסד יומי, ירידה מהשיא, margin, נתונים טריים, כפילויות. מודל שפה לא שולח פקודות.</div>`)}
    ${sec('יומן', jBlock)}
    ${policyCard(P, r.strategies)}
    ${disclaimer('סימולציה של חשבון margin. עמלות, ריבית, השאלה, slippage וחיסול כפוי מקורבים למחירון IBKR ואינם התחייבות. שום דבר כאן אינו ייעוץ השקעות.')}
  </div>`;
  const put = (id, node) => { const h = main.querySelector('#' + id); if (h && node) h.appendChild(node); };
  put('ch-eq', equityChart(eq));
  const bc = Object.entries(ex.byClass || {}); if (bc.length) put('ch-class', barChart({ labels: bc.map(([k]) => CLASS_HE[k] || k), values: bc.map(([, v]) => v), height: 140, horizontal: true, yFmt: (v) => usd(v) }));
  const bs = Object.entries(ex.byStrategy || {}); if (bs.length) put('ch-strat', barChart({ labels: bs.map(([k]) => k), values: bs.map(([, v]) => v), height: 140, horizontal: true, yFmt: (v) => usd(v) }));
  main.querySelectorAll('[data-kill]').forEach((b) => { b.onclick = async () => { const on = b.dataset.kill === '1'; if (on && !confirm('לעצור את הסוכן? לא יישלחו פקודות חדשות (גם לא סגירות אוטומטיות) עד שתבטל.')) return; b.disabled = true; try { await api('/agent/kill?on=' + (on ? '1' : '0'), { method: 'POST', body: { reason: on ? 'נעצר ידנית מהאפליקציה' : null }, auth: true }); invalidate('/agent'); toast(on ? 'הסוכן נעצר' : 'הסוכן חזר לפעול'); render(main); } catch (e) { toast('נכשל: ' + (e.message || e), 'err'); b.disabled = false; } }; });
}

function policyCard(P, S){
  const lim = [['הון בסימולציה', fmt.ils(P.capitalIls)], ['מינוף כולל', '×' + (P.leverage?.total ?? '—')], ['לפי סוג', Object.entries(P.leverage?.byClass || {}).filter(([k]) => ['stock', 'etf', 'crypto', 'fx', 'future'].includes(k)).map(([k, v]) => `${CLASS_HE[k] || k} ×${v}`).join(', ')], ['שורט', P.shorting ? 'מותר' : 'אסור'], ['פקודה אחת', fmt.pct(P.maxTradeShare, 0) + ' מההון'], ['נייר אחד', fmt.pct(P.maxAssetShare, 0)], ['תקרות לסוג', Object.entries(P.maxClassShare || {}).map(([k, v]) => `${CLASS_HE[k] || k} ${fmt.pct(v, 0)}`).join(', ')], ['הפסד יומי → עצירה', fmt.pct(P.maxDailyLoss, 0)], ['ירידה מהשיא → עצירה', fmt.pct(P.maxDrawdown, 0)], ['פקודות ביום', P.maxOrdersPerDay]];
  return sec('המדיניות (קובץ מוגן, שינוי דורש אישור בעל הריפו)', `<div class="grid g2">${lim.map(([l, v]) => `<div class="kpi"><span class="v" style="font-size:1rem">${v ?? '—'}</span><span class="l">${esc(l)}</span></div>`).join('')}</div>
    <div class="muted" style="font-size:.82rem;margin-top:.5rem">גרסה ${P.version ?? '—'} · מצב <b>${esc(P.mode || '')}</b> · hash <code>${esc(P.hash || '')}</code> · כסף אמיתי דורש אישור נפרד עם hash תואם — לא קיים.</div>
    <div class="muted" style="font-size:.82rem;margin-top:.3rem">אסטרטגיות: ${Object.entries(S || {}).map(([k, s]) => `<b>${esc(k)}</b> ${esc(s.label)} (${s.horizonDays} ימים, סיכון ${fmt.pct(s.riskPct, 2)} לעסקה)`).join(' · ')}</div>
    <div class="row" style="margin-top:.6rem;gap:.5rem">${P.killSwitch ? '<button class="btn" data-kill="0">▶️ בטל את העצירה</button>' : '<button class="btn danger" data-kill="1">⛔ עצור את הסוכן (kill switch)</button>'}</div>`, 'AI_COUNCIL#21');
}
