// דף נכס: ציון+סיגנל+WHY, פונדמנטלס, טכני, חדשות, אנליסטים, סיכון, היסטוריית סיגנלים. כל בלוק עם מקור וחותמת.
import { api, getBundle, invalidate } from '../core/api.js';
import { run } from '../core/compute.js';
import { settings } from '../core/store.js';
import { el, esc, fmt, isNum, cls, modal, toast, COMP_HE } from '../core/util.js';
import { sigBadge, scoreBar, kind, missing, asOf, kpi, pctCell, confBadge, whyBlock, componentsTable, loading, errorBox, disclaimer } from '../ui/components.js';
import { priceChart, lineChart, barChart } from '../ui/chart.js';

const KIND_ROW = (k) => (k === 'derived' ? kind('FACT') : k === 'provider' ? kind('FACT') : k === 'estimate' ? kind('ESTIMATE') : '');
const num = (x, d = 2) => (isNum(x) ? `<span class="num">${fmt.num(x, d)}</span>` : missing());
const pct = (x) => (isNum(x) ? pctCell(x, 1) : missing());

export async function render(main, { symbol }){
  const s = String(symbol || '').toUpperCase();
  main.innerHTML = loading(`מנתח ${s}…`);
  let a, mode = 'server';
  try { a = await api(`/asset/${s}`); }
  catch (e) {
    // Fallback: חישוב בדפדפן מאותו engine (למשל כשה-Worker חורג ממגבלת CPU של התוכנית החינמית)
    try {
      const [b, regime, spy, dgs] = await Promise.all([getBundle(s), api('/regime', { ttl: 60000 }).catch(() => null), api('/prices/SPY?from=2022-01-01', { ttl: 600000 }).catch(() => null), api('/macro', { ttl: 600000 }).catch(() => null)]);
      if (!b.prices || b.prices.missing) throw new Error(b.prices?.reason || 'אין מחירים');
      a = await run('analyzeOne', { bundle: { ...b, quote: null, news: null, analyst: null }, regime, benchRows: spy?.rows, dgs10Rows: dgs?.DGS10?.rows, weights: null });
      mode = 'browser'; toast('ה-API לא ענה — הניתוח חושב בדפדפן מנתוני bundle (ללא quote/חדשות/אנליסטים)', 'err');
    } catch (e2) { main.innerHTML = errorBox(e) + errorBox(e2); return; }
  }
  if (a.missing){ main.innerHTML = `<div class="page-head"><h1>${esc(s)}</h1></div><div class="empty">Missing Data: ${esc(a.reason)}</div>`; return; }
  const sig = a.signal, sc = a.score, t = a.technical, m = a.metrics, fv = a.fair, r = a.risk, an = a.analyst, d = a.dataAsOf, lv = sig.levels;
  const isEtf = ['etf', 'index', 'fund'].includes(a.asset.type);
  main.innerHTML = `
  <div class="page-head"><div><h1>${esc(a.asset.nameHe || a.asset.name || a.asset.symbol)} <span class="muted" style="font-weight:400">${esc(a.asset.symbol)}${a.asset.nameHe ? ' · ' + esc(a.asset.name || '') : ''}</span></h1>
    <div class="row muted"><span>${esc(a.asset.type)}</span>·<span>${esc(a.asset.sector || '')}</span>·<span>${esc(a.asset.country || '')}</span>·<span>${esc(a.asset.currency || '')}</span>${a.asset.marketCap ? `·<span>שווי שוק ${fmt.big(a.asset.marketCap)}</span>` : ''}${mode === 'browser' ? '·<span class="tag stale">חושב בדפדפן</span>' : ''}</div></div>
    <div class="row"><button class="btn" id="watchBtn">${a.watched ? '★ במעקב' : '☆ הוסף למעקב'}</button><button class="btn" id="paperBtn">🧾 Paper Buy</button><button class="btn" id="alertBtn">🔔 התראה</button><button class="btn ghost sm" id="refreshBtn" title="רענון מהספקים (דורש טוקן)">⟳</button></div></div>
  <div class="grid g4" style="margin-bottom:1rem">
    <div class="card"><div class="kpi"><span class="v">${fmt.num(a.price)} <small class="${cls(a.dailyChange)}">${fmt.pct(a.dailyChange, 2, true)}</small></span><span class="l">מחיר ${kind('FACT')} ${asOf(a.priceSource?.asOf, { source: a.priceSource?.source })} ${a.priceSource?.kind === 'close' ? '<span class="tag">סגירה</span>' : ''}</span></div></div>
    <div class="card"><div class="kpi"><span class="v">${sigBadge(sig.label)}</span><span class="l">סיגנל ${kind('MODEL SIGNAL')} · אופק ${esc(sig.horizon || '—')} · ${confBadge(sig.confidence, sig.confidenceLabel)}</span></div></div>
    <div class="card"><div class="kpi"><span class="v">${scoreBar(sc.total)}</span><span class="l">Investment Score ${kind('MODEL')} · כיסוי ${fmt.pct(sc.coverage, 0)}</span></div></div>
    <div class="card"><div class="kpi"><span class="v">${lv ? `<span class="num">${lv.rr ?? '—'}</span>` : '—'}</span><span class="l">Risk/Reward · Upside ${fmt.pct(lv?.upside, 0, true)} · Downside ${fmt.pct(lv?.downside, 0, true)}</span></div></div>
  </div>
  ${sig.label === 'NO SIGNAL' ? `<div class="card" style="border-color:var(--warn);margin-bottom:1rem"><b>NO SIGNAL:</b> ${esc(sig.noSignalReason || '')}. רכיבים חסרים: ${esc((sc.missing || []).map((x) => x.label + ' (' + x.reason + ')').join('; ') || '—')}</div>` : ''}
  <div class="tabs" id="tabs"><button class="active" data-t="overview">סקירה ו-WHY</button><button data-t="tech">טכני</button><button data-t="fund">פונדמנטלי</button><button data-t="val">הערכת שווי</button><button data-t="news">חדשות</button><button data-t="analyst">אנליסטים</button><button data-t="risk">סיכון</button><button data-t="hist">היסטוריה</button></div>
  <div id="tab"></div>${disclaimer()}`;
  const tab = main.querySelector('#tab');
  const tabs = {
    overview: () => `<div class="grid g-2-1"><section class="card"><h3>למה ${esc(sig.label)}? ${kind('MODEL SIGNAL')}</h3>${whyBlock(sig)}
      ${lv ? `<h4 style="margin-top:.8rem">רמות</h4><dl class="kv"><dt>Entry Zone</dt><dd>${lv.entryZone[0]} – ${lv.entryZone[1]} <span class="muted">${esc(sig.entryNote || '')}</span></dd><dt>Invalidation</dt><dd>${lv.invalidation}</dd><dt>Stop / Trailing</dt><dd>${lv.stop} / ${lv.trailingStop ?? '—'} (3×ATR)</dd><dt>Target Range</dt><dd>${lv.targets[0]} – ${lv.targets[1]} <span class="muted">${esc(lv.targetBasis)}</span></dd><dt>Expected Upside</dt><dd class="pos">${fmt.pct(lv.upside, 1, true)}</dd><dt>Potential Downside</dt><dd class="neg">${fmt.pct(lv.downside, 1, true)}</dd><dt>R/R</dt><dd>${lv.rr ?? '—'}</dd><dt>Time Horizon</dt><dd>${esc(sig.horizon || '—')}</dd></dl>` : ''}</section>
      <section class="card"><h3>רכיבי הציון</h3>${componentsTable(sc)}<div class="row" style="margin-top:.5rem"><a href="#/settings" class="muted">שינוי משקלים →</a></div></section></div>
      <section class="card" style="margin-top:1rem"><h3>מקורות וחותמות עדכון</h3><div class="row">${Object.entries(d || {}).map(([k, v]) => v ? `<span class="tag ${v.missing ? 'missing' : v.stale ? 'stale' : ''}">${esc(k)}: ${v.missing ? 'חסר — ' + esc(v.reason || '') : esc(v.source || (v.sources || []).join('+')) + ' · ' + esc(fmt.date(v.asOf)) + (isNum(v.quality) ? ' · q' + v.quality : '')}</span>` : '').join('')}</div></section>`,
    tech: () => { const box = el('<div class="stack"></div>'); box.innerHTML = `<section class="card"><h3>גרף מחיר ואינדיקטורים ${kind('FACT')} <span class="row"><button class="btn sm" data-r="126">6M</button><button class="btn sm" data-r="252">1Y</button><button class="btn sm" data-r="756">3Y</button><button class="btn sm" data-r="2500">הכול</button></span></h3><div id="pc">${loading()}</div></section>
      <section class="card"><h3>מדדים טכניים <span class="muted">${esc(t.date)}</span></h3><div class="grid g4">${kpi('SMA 20 / 50', `${fmt.num(t.sma.s20)} / ${fmt.num(t.sma.s50)}`)}${kpi('SMA 100 / 200', `${fmt.num(t.sma.s100)} / ${fmt.num(t.sma.s200)}`)}${kpi('EMA 20 / 50', `${fmt.num(t.ema?.e20)} / ${fmt.num(t.ema?.e50)}`)}${kpi('RSI 14', fmt.num(t.rsi, 1), t.rsi > 70 ? 'neg' : t.rsi < 30 ? 'warn' : '')}${kpi('MACD / signal / hist', `${fmt.num(t.macd.line)} / ${fmt.num(t.macd.signal)} / ${fmt.num(t.macd.hist)}`)}${kpi('Bollinger %B / width', `${fmt.num(t.bb.pctB)} / ${fmt.pct(t.bb.width, 1)}`)}${kpi('ATR 14 (%)', `${fmt.num(t.atr)} (${fmt.pct(t.atrPct, 2)})`)}${kpi('מחזור / ממוצע 20 / יחסי', `${fmt.big(t.volume)} / ${fmt.big(t.avgVolume20)} / ${fmt.x(t.relVol, 1)}`)}${kpi('שיא / שפל 52 שבועות', `${fmt.num(t.high52)} / ${fmt.num(t.low52)}`)}${kpi('מרחק משיא / משפל', `${fmt.pct(t.distFromHigh52, 1)} / ${fmt.pct(t.distFromLow52, 1, true)}`)}${kpi('מגמה', `${esc(t.trend)} (${t.trendScore})`)}${kpi('מומנטום 1M/3M/6M/12M', `${fmt.pct(t.momentum.r1m, 0, true)} / ${fmt.pct(t.momentum.r3m, 0, true)} / ${fmt.pct(t.momentum.r6m, 0, true)} / ${fmt.pct(t.momentum.r12m, 0, true)}`)}${kpi('תנודתיות שנתית / 6M', `${fmt.pct(t.vol1y, 0)} / ${fmt.pct(t.vol6m, 0)}`)}${kpi('Drawdown נוכחי / מקס׳ שנה', `${fmt.pct(t.currentDrawdown, 0)} / ${fmt.pct(t.maxDrawdown1y, 0)}`)}${kpi('תמיכות', (t.supports || []).map((x) => x.level).join(' · ') || '—')}${kpi('התנגדויות', (t.resistances || []).map((x) => x.level).join(' · ') || '—')}</div>
      <h4 style="margin-top:.8rem">אירועים שזוהו</h4><div class="row">${t.events.length ? t.events.map((e) => `<span class="tag ${e.tone === 'pos' ? 'fact' : e.tone === 'neg' ? 'missing' : 'stale'}">${esc(e.label)}${e.date ? ' · ' + esc(e.date) : ''}</span>`).join('') : '<span class="muted">אין אירועים טכניים כרגע</span>'}</div><p class="muted">אף אינדיקטור בודד אינו אות קנייה; הסיגנל משקלל מבנה מגמה, מומנטום, סיכון ופונדמנטלס.</p></section>`;
      (async () => { try { const b = await getBundle(s); const ind = await run('indicators', { rows: b.prices.rows }); let range = 252; const draw = () => { const pc = box.querySelector('#pc'); pc.innerHTML = ''; pc.appendChild(priceChart({ dates: ind.dates, close: ind.close, sma20: ind.sma20, sma50: ind.sma50, sma200: ind.sma200, bb: ind.bb, volume: ind.volume, rsi: ind.rsi, macd: ind.macd, levels: lv, range })); }; box.querySelectorAll('[data-r]').forEach((btn) => btn.onclick = () => { range = +btn.dataset.r; draw(); }); draw(); } catch (e) { box.querySelector('#pc').innerHTML = errorBox(e); } })();
      return box; },
    fund: () => { if (!m || m.missing) return `<div class="empty">Missing Data: ${esc(m?.reason || 'אין פונדמנטלס')}${isEtf && a.etf ? '' : ''}</div>` + (a.etf ? etfBlock(a.etf) : ''); const f = m.fields || {}; const row = (label, key, fmtFn = pct) => `<tr><td>${label}</td><td class="num">${fmtFn(m[key])}</td><td>${f[key] ? `<span class="muted">${esc(f[key].source)}</span> ${KIND_ROW(f[key].kind)}` : (isNum(m[key]) ? kind('FACT') : '')}</td></tr>`;
      return `<div class="grid g2"><section class="card"><h3>דוחות (TTM) ${kind('FACT')} <span class="muted">${esc(m.source || '')} · ${esc(m.basis || '')} · עד ${esc(fmt.date(m.asOf))}${m.filed ? ' · הוגש ' + esc(m.filed) : ''}</span></h3><table><tbody>
        ${row('Revenue', 'revenue', (x) => num(x / 1e6, 0) + ' M')}${row('Revenue Growth (YoY)', 'revenueGrowth')}${row('Revenue CAGR 3Y', 'revenueCagr3y')}${row('EPS (מדולל)', 'eps', (x) => num(x, 2))}${row('EPS Growth', 'epsGrowth')}${row('Net Income', 'netIncome', (x) => num(x / 1e6, 0) + ' M')}${row('Gross / Operating / Net margin', 'netMargin', () => `${fmt.pct(m.grossMargin, 1)} / ${fmt.pct(m.operatingMargin, 1)} / ${fmt.pct(m.netMargin, 1)}`)}${row('Free Cash Flow', 'fcf', (x) => num(x / 1e6, 0) + ' M')}${row('FCF margin', 'fcfMargin')}${row('Cash', 'cash', (x) => num(x / 1e6, 0) + ' M')}${row('Total Debt / Net Debt', 'totalDebt', () => `${fmt.big(m.totalDebt)} / ${fmt.big(m.netDebt)}`)}${row('ROE', 'roe')}${row('ROIC (3Y avg)', 'roic', () => `${fmt.pct(m.roic, 1)} (${fmt.pct(m.roicAvg3y, 1)})`)}${row('Net Debt / EBITDA', 'netDebtToEbitda', (x) => num(x, 2))}${row('Interest coverage', 'interestCoverage', (x) => (isNum(x) ? fmt.x(x, 1) : missing()))}${row('Cash conversion (FCF/NI)', 'cashConversion', (x) => num(x, 2))}${row('דילול מניות 3Y', 'dilution3y')}${row('Dividend yield', 'dividendYield')}${row('Dividend growth 5Y', 'dividendGrowth5y')}</tbody></table></section>
      <section class="card"><h3>מכפילים ${kind('FACT')}/${kind('ESTIMATE')}</h3><table><tbody>${row('P/E (TTM)', 'pe', (x) => (m.peNegative ? '<span class="tag">רווח שלילי</span>' : num(x, 1)))}${row('Forward P/E', 'forwardPe', (x) => num(x, 1))}${row('PEG', 'peg', (x) => num(x, 2))}${row('P/S', 'ps', (x) => num(x, 2))}${row('EV/EBITDA', 'evEbitda', (x) => num(x, 1))}${row('FCF Yield', 'fcfYield')}${row('Market Cap / EV', 'marketCap', () => `${fmt.big(m.marketCap)} / ${fmt.big(m.ev)}`)}</tbody></table>
      ${a.estimates && !a.estimates.missing ? `<h4 style="margin-top:.8rem">תחזיות אנליסטים ${kind('ESTIMATE')} <span class="muted">${esc(a.estimates.source)} · ${esc(fmt.date(a.estimates.asOf))}</span></h4><dl class="kv"><dt>EPS FY1 / FY2</dt><dd>${fmt.num(a.estimates.eps?.fy1)} / ${fmt.num(a.estimates.eps?.fy2)}</dd><dt>Revenue FY1 / FY2</dt><dd>${fmt.big(a.estimates.revenue?.fy1)} / ${fmt.big(a.estimates.revenue?.fy2)}</dd></dl>` : '<p class="muted">תחזיות EPS/Revenue: Missing Data (דורש FMP)</p>'}
      ${m.history?.revenue?.length ? `<h4 style="margin-top:.8rem">היסטוריה שנתית</h4>${barChart({ labels: m.history.revenue.map((x) => x[0].slice(0, 4)), values: m.history.revenue.map((x) => x[1] / 1e6), height: 140, color: '#4f8cff', yFmt: (v) => fmt.big(v * 1e6) }).outerHTML}<div class="muted">הכנסות (M)</div>${barChart({ labels: m.history.eps.map((x) => x[0].slice(0, 4)), values: m.history.eps.map((x) => x[1]), height: 120 }).outerHTML}<div class="muted">EPS</div>` : ''}</section></div>
      <p class="muted">השוואה להיסטוריית החברה: ראו לשונית "הערכת שווי" (P/E היסטורי) ורכיב Valuation (אחוזון). השוואה לעמיתים: מחושבת מנכסים באותו ענף ב-universe כשיש snapshot.</p>`; },
    val: () => { if (!fv || fv.missing) return `<div class="empty">Missing Data: ${esc(fv?.reason || '')}</div>`; return `<section class="card"><h3>Fair Value Range ${kind('MODEL')}</h3><div class="grid g4">${kpi('טווח שווי הוגן', `<span class="num">${fv.low} – ${fv.high}</span>`)}${kpi('אמצע', fmt.num(fv.mid))}${kpi('מחיר', fmt.num(fv.price))}${kpi('Margin of Safety (מול הרצפה)', fmt.pct(fv.marginOfSafety, 1, true), cls(fv.marginOfSafety))}</div>
      <table style="margin-top:.8rem"><thead><tr><th>שיטה</th><th class="num">נמוך</th><th class="num">גבוה</th><th>פרטים</th><th>סוג</th></tr></thead><tbody>${fv.methods.map((x) => `<tr><td>${esc(x.label)}</td><td class="num">${x.low}</td><td class="num">${x.high}</td><td style="white-space:normal">${esc(x.detail)}</td><td>${esc(x.kind)}</td></tr>`).join('')}</tbody></table><p class="muted">${esc(fv.note)} הטווח = חציון הרצפות וחציון התקרות של השיטות.</p></section>`; },
    news: () => { const cl = a.sentiment?.clusters || a.bundle?.newsClusters || []; return `<section class="card"><h3>חדשות וסנטימנט <span class="muted">${a.sentiment?.missing ? esc(a.sentiment.reason) : `ציון ${a.sentiment.value}/100 · ${a.sentiment.count} ידיעות ייחודיות · ${a.sentiment.materialCount} מהותיות`}</span></h3>
      ${a.sentiment?.reasons ? `<ul class="list muted">${a.sentiment.reasons.map((x) => `<li>${esc(x)}</li>`).join('')}</ul>` : ''}
      ${cl.length ? `<table><thead><tr><th>תאריך</th><th>ידיעה</th><th>מקור</th><th>סנטימנט</th><th>אירועים</th><th>כפילויות</th></tr></thead><tbody>${cl.map((n) => `<tr><td class="num">${fmt.date(n.publishedAt)}</td><td style="white-space:normal"><a href="${esc(n.url)}" target="_blank" rel="noopener">${esc(n.title)}</a>${n.material ? ' <span class="tag opinion">מהותי</span>' : ''}</td><td>${esc(n.publisher || '')} ${n.primary ? '<span class="tag fact">ראשוני</span>' : ''}</td><td class="${n.sentiment.score > 0.15 ? 'pos' : n.sentiment.score < -0.15 ? 'neg' : ''}">${esc(n.sentiment.label)} <span class="muted">(${n.sentiment.score}, ${esc(n.sentiment.method)})</span></td><td>${(n.events || []).map((e) => `<span class="tag">${esc(e)}</span>`).join(' ')}</td><td class="num" title="${esc((n.cluster?.sources || []).join(', '))}">${n.cluster?.size > 1 ? `×${n.cluster.size}` : ''}</td></tr>`).join('')}</tbody></table>` : '<div class="empty">אין חדשות (Missing Data)</div>'}
      ${a.insider?.length ? `<h4 style="margin-top:.8rem">עסקאות בעלי עניין ${kind('FACT')}</h4><table><thead><tr><th>תאריך</th><th>שם</th><th>סוג</th><th class="num">מניות</th><th class="num">מחיר</th><th>מקור</th></tr></thead><tbody>${a.insider.map((i) => `<tr><td class="num">${fmt.date(i.date)}</td><td>${esc(i.name || '')} <span class="muted">${esc(i.role || '')}</span></td><td class="${i.type === 'buy' ? 'pos' : 'neg'}">${i.type === 'buy' ? 'קנייה' : 'מכירה'}</td><td class="num">${fmt.big(i.shares)}</td><td class="num">${fmt.num(i.price)}</td><td class="muted">${esc(i.source)}</td></tr>`).join('')}</tbody></table>` : ''}
      <p class="muted">Short interest / החזקות מוסדיות: Missing Data (אין מקור חינמי מורשה — ראו DATA_SOURCES.md).</p></section>`; },
    analyst: () => { if (!an || an.missing) return `<div class="empty">Missing Data: ${esc(an?.reason || 'אין קונצנזוס אנליסטים')}</div>`; const tg = an.targets || {}; const bars = [['Strong Buy', an.strongBuy], ['Buy', an.buy], ['Hold', an.hold], ['Sell', an.sell], ['Strong Sell', an.strongSell]]; return `<section class="card"><h3>קונצנזוס אנליסטים ${kind('ANALYST OPINION')} <span class="muted">${esc((an.sources || [an.source]).join(' + '))} · ${esc(fmt.date(an.asOf))}</span></h3>
      <div class="grid g2"><div>${barChart({ labels: bars.map((b) => b[0]), values: bars.map((b) => b[1] || 0), height: 160, colors: ['#1f9d55', '#2fbf71', '#94a3b8', '#f5a524', '#e5484d'], yFmt: (v) => String(Math.round(v)) }).outerHTML}<div class="muted">${an.total} אנליסטים${isNum(an.trendDelta) ? ` · שינוי חודשי ב-Buy+SB: ${an.trendDelta > 0 ? '+' : ''}${an.trendDelta}` : ''}</div></div>
      <div><dl class="kv"><dt>Average Target</dt><dd>${fmt.num(tg.avg)}</dd><dt>Median Target</dt><dd>${fmt.num(tg.median)}</dd><dt>Highest</dt><dd>${fmt.num(tg.high)}</dd><dt>Lowest</dt><dd>${fmt.num(tg.low)}</dd><dt>Upside/Downside (מול ${fmt.num(a.price)})</dt><dd class="${cls((tg.median || tg.avg) / a.price - 1)}">${isNum(tg.median || tg.avg) ? fmt.pct((tg.median || tg.avg) / a.price - 1, 1, true) : 'Missing Data'}</dd></dl>
      ${an.history?.length ? `<h4 style="margin-top:.6rem">שינויים אחרונים</h4><table><thead><tr><th>תקופה</th><th class="num">SB</th><th class="num">B</th><th class="num">H</th><th class="num">S</th><th class="num">SS</th></tr></thead><tbody>${an.history.map((h) => `<tr><td>${esc(h.period)}</td><td class="num">${h.strongBuy}</td><td class="num">${h.buy}</td><td class="num">${h.hold}</td><td class="num">${h.sell}</td><td class="num">${h.strongSell}</td></tr>`).join('')}</tbody></table>` : ''}
      ${a.earnings ? `<h4 style="margin-top:.6rem">דוחות</h4><dl class="kv"><dt>הדוח הבא</dt><dd>${fmt.date(a.earnings.next) || 'Missing'}</dd>${(a.earnings.last || []).map((e) => `<dt>${esc(e.date || e.period)}</dt><dd>EPS ${fmt.num(e.epsActual)} מול ${fmt.num(e.epsEst)} (${fmt.pct(e.surprisePct, 1, true)})</dd>`).join('')}</dl>` : ''}</div></div>
      <p class="muted">קונצנזוס אנליסטים הוא דעה — משקלו במודל ${sc.components?.analyst?.weight ?? 8}% בלבד, ומוקטן כשהמדגם קטן מ-5.</p></section>`; },
    risk: () => (!r || r.missing ? `<div class="empty">${esc(r?.reason || '')}</div>` : `<section class="card"><h3>מנוע סיכון ${kind('MODEL')}</h3><div class="grid g4">${kpi('תנודתיות שנתית / 3M', `${fmt.pct(r.vol1y, 0)} / ${fmt.pct(r.vol3m, 0)}`)}${kpi('בטא מול SPY (קורלציה)', `${fmt.num(r.beta)} (${fmt.num(r.correlationToBenchmark)})`)}${kpi('בטא מול QQQ', fmt.num(r.techBeta))}${kpi('Max DD שנה / 3 שנים', `${fmt.pct(r.maxDrawdown1y, 0)} / ${fmt.pct(r.maxDrawdown3y, 0)}`)}${kpi('נזילות ($ יומי)', `${fmt.big(r.avgDollarVolume20)} · ${esc(r.liquidity)}`)}${kpi('Gap risk (ימים |gap|>5%)', `${fmt.pct(r.gapRate, 1)} · ${esc(r.gapRisk)}`)}${kpi('Earnings risk', `${esc(r.earningsRisk)}${isNum(r.earningsInDays) ? ` (${r.earningsInDays} ימים)` : ''}`)}${kpi('סיכון מטבע', esc(r.currencyRisk))}</div><p class="muted">${esc(r.summary)}. סיכון מטבע: משקיע שקלי בנכס דולרי חשוף ל-USD/ILS — ראו תרחישים בעמוד התיק.</p></section>`),
    hist: () => { const h = a.history || []; if (!h.length) return '<div class="empty">אין snapshots שמורים עדיין (נוצרים בעיבוד היומי — ולא נדרסים)</div>'; return `<section class="card"><h3>היסטוריית ציון וסיגנל <span class="muted">append-only · ${h.length} ימים</span></h3>${lineChart({ dates: h.map((x) => x.date), height: 200, series: [{ name: 'ציון', values: h.map((x) => x.score), color: '#a78bfa' }], yDomain: [0, 100] }).outerHTML}${lineChart({ dates: h.map((x) => x.date), height: 160, series: [{ name: 'מחיר', values: h.map((x) => x.price), color: '#4f8cff' }] }).outerHTML}<table><thead><tr><th>תאריך</th><th class="num">ציון</th><th>סיגנל</th><th class="num">מחיר</th></tr></thead><tbody>${h.slice().reverse().slice(0, 60).map((x) => `<tr><td class="num">${esc(x.date)}</td><td class="num">${x.score ?? '—'}</td><td>${sigBadge(x.signal)}</td><td class="num">${fmt.num(x.price)}</td></tr>`).join('')}</tbody></table><a href="#/asof?symbol=${esc(s)}" class="muted">בדוק "מה המערכת הייתה יודעת בתאריך X" →</a></section>`; },
  };
  const show = (k) => { const v = tabs[k](); tab.innerHTML = ''; if (typeof v === 'string') tab.innerHTML = v; else tab.appendChild(v); };
  main.querySelector('#tabs').addEventListener('click', (e) => { const b = e.target.closest('button'); if (!b) return; main.querySelectorAll('#tabs button').forEach((x) => x.classList.toggle('active', x === b)); show(b.dataset.t); });
  show('overview');
  main.querySelector('#watchBtn').onclick = async () => { try { if (a.watched) await api('/watchlist?symbol=' + s, { method: 'DELETE' }); else await api('/watchlist', { method: 'POST', body: { symbol: s } }); invalidate('/watchlist'); invalidate(`/asset/${s}`); toast(a.watched ? 'הוסר מהמעקב' : 'נוסף למעקב'); render(main, { symbol: s }); } catch (e) { toast(e.message, 'err'); } };
  main.querySelector('#refreshBtn').onclick = async () => { try { invalidate(`/asset/${s}`); toast('מרענן מהספקים…'); await api(`/asset/${s}?refresh=1`, { auth: true }); render(main, { symbol: s }); } catch (e) { toast(e.message, 'err'); } };
  main.querySelector('#paperBtn').onclick = () => { const mm = modal(`<h2>Paper Buy — ${esc(s)}</h2><p class="muted">מחיר ביצוע: ${fmt.num(a.price)} (${esc(a.priceSource?.source || '')}) · סיגנל ${esc(sig.label)}</p><div class="stack"><label>כמות <input id="qty" type="number" value="10" min="0.01" step="1"></label><label>סיבה <input id="reason" value="${esc(sig.label)} · ציון ${sc.total}"></label><div class="row"><button class="btn primary" id="ok">בצע קנייה וירטואלית</button><button class="btn" data-close>ביטול</button></div></div>`); mm.el.querySelector('#ok').onclick = async () => { try { await api('/paper/order', { method: 'POST', body: { symbol: s, side: 'buy', qty: +mm.el.querySelector('#qty').value, reason: mm.el.querySelector('#reason').value } }); invalidate('/paper'); toast('נרשם בתיק הווירטואלי'); mm.close(); } catch (e) { toast(e.message, 'err'); } }; };
  main.querySelector('#alertBtn').onclick = async () => { const types = await api('/alerts/types', { ttl: 600000 }); const mm = modal(`<h2>התראה על ${esc(s)}</h2><div class="stack"><select id="type">${Object.entries(types).map(([k, v]) => `<option value="${k}">${esc(v.label)}</option>`).join('')}</select><label>פרמטרים (JSON) <input id="params" value="{}"></label><div class="row"><label><input type="checkbox" value="browser" checked> דפדפן</label><label><input type="checkbox" value="telegram"> Telegram</label><label><input type="checkbox" value="email"> אימייל</label></div><div class="row"><button class="btn primary" id="ok">שמור</button><button class="btn" data-close>ביטול</button></div></div>`); mm.el.querySelector('#ok').onclick = async () => { try { const channels = [...mm.el.querySelectorAll('input[type=checkbox]:checked')].map((c) => c.value); await api('/alerts/rules', { method: 'POST', body: { symbol: s, type: mm.el.querySelector('#type').value, params: JSON.parse(mm.el.querySelector('#params').value || '{}'), channels } }); toast('הכלל נשמר'); mm.close(); } catch (e) { toast(e.message, 'err'); } }; };
}
function etfBlock(e){ return `<section class="card"><h3>ETF — החזקות ${kind('FACT')} <span class="muted">${esc(e.source)} · ${esc(fmt.date(e.asOf))}</span></h3><div class="grid g2"><div><dl class="kv"><dt>Expense ratio</dt><dd>${fmt.pct(e.expense, 2)}</dd><dt>AUM</dt><dd>${fmt.big(e.aum)}</dd><dt>תשואת דיבידנד</dt><dd>${fmt.pct(e.dividendYield, 2)}</dd></dl>${(e.sectors || []).length ? `<h4>ענפים</h4><ul class="list">${e.sectors.slice(0, 8).map((x) => `<li>${esc(x.sector)}: <span class="num">${fmt.pct(x.weight, 1)}</span></li>`).join('')}</ul>` : ''}</div><div><h4>החזקות עיקריות</h4><table><tbody>${(e.holdings || []).slice(0, 15).map((h) => `<tr><td><a href="#/asset/${esc(h.symbol)}">${esc(h.symbol)}</a> <span class="muted">${esc(h.name || '')}</span></td><td class="num">${fmt.pct(h.weight, 2)}</td></tr>`).join('')}</tbody></table></div></div><p class="muted">ETF flows: Missing Data (אין מקור חינמי).</p></section>`; }
