// Backtest בדפדפן (Web Worker): אסטרטגיות, תקופות, Walk-Forward, השוואה ל-Buy&Hold ול-benchmark.
import { api, getBundle } from '../core/api.js';
import { run } from '../core/compute.js';
import { esc, fmt, isNum, cls, toast } from '../core/util.js';
import { kind, loading, errorBox, disclaimer, kpi } from '../ui/components.js';
import { lineChart } from '../ui/chart.js';

const STRATS = { buyhold: 'Buy & Hold', trend: 'מגמה (SMA200 + SMA50)', momentum: 'מומנטום 12−1', meanrev: 'חזרה לממוצע (RSI)', signal: 'סיגנל המערכת (BUY↔SELL + stop)' };
const mrow = (label, m, bh, bm) => `<tr><td>${label}</td><td class="num">${m}</td><td class="num">${bh}</td><td class="num">${bm ?? '—'}</td></tr>`;
export function metricsTable(m, bh, bm){ if (!m) return '<div class="muted">—</div>'; const P = (x) => fmt.pct(x, 1, true), N = (x, d = 2) => fmt.num(x, d); return `<table><thead><tr><th>מדד</th><th class="num">אסטרטגיה</th><th class="num">Buy & Hold</th><th class="num">Benchmark</th></tr></thead><tbody>${mrow('CAGR', P(m.cagr), P(bh?.cagr), bm && P(bm.cagr))}${mrow('Total Return', P(m.totalReturn), P(bh?.totalReturn), bm && P(bm.totalReturn))}${mrow('Annualized Vol', P(m.volatility), P(bh?.volatility), bm && P(bm.volatility))}${mrow('Sharpe', N(m.sharpe), N(bh?.sharpe), bm && N(bm.sharpe))}${mrow('Sortino', N(m.sortino), N(bh?.sortino), bm && N(bm.sortino))}${mrow('Max Drawdown', P(m.maxDrawdown), P(bh?.maxDrawdown), bm && P(bm.maxDrawdown))}${mrow('Calmar', N(m.calmar), N(bh?.calmar), bm && N(bm.calmar))}${mrow('Win Rate', fmt.pct(m.winRate, 0), '—', '—')}${mrow('Profit Factor', m.profitFactor === Infinity ? '∞' : N(m.profitFactor), '—', '—')}${mrow('Number of Trades', m.trades, '1', '1')}${mrow('Exposure', fmt.pct(m.exposure, 0), '100%', '100%')}${mrow('Avg / Best / Worst trade', `${P(m.avgTradePct)} / ${P(m.bestTradePct)} / ${P(m.worstTradePct)}`, '—', '—')}</tbody></table>`; }

export async function render(main, params = {}){
  main.innerHTML = `<div class="page-head"><div><h1>Backtest</h1><span class="muted">${kind('MODEL')} · רץ בדפדפן על נתוני ה-API · ביצוע ב-Open העוקב · עמלה 0.1% + slippage 0.05% לכל צד</span></div></div>
  <div class="card tight toolbar"><input id="sym" value="${esc(params.symbol || 'SPY')}" style="width:110px" placeholder="סימבול"><select id="strat">${Object.entries(STRATS).map(([k, v]) => `<option value="${k}">${esc(v)}</option>`).join('')}</select><label class="muted">מ- <input id="from" type="date" value="2015-01-01"></label><label class="muted">עד <input id="to" type="date"></label><label class="muted">עמלה % <input id="comm" type="number" value="0.1" step="0.05" style="width:64px"></label><label class="muted">slippage % <input id="slip" type="number" value="0.05" step="0.05" style="width:64px"></label><select id="bench"><option value="SPY">Benchmark: SPY</option><option value="QQQ">QQQ</option><option value="IWM">IWM</option><option value="AGG">AGG</option></select><button class="btn primary" id="go">הרץ</button></div>
  <div id="out"><div class="empty">בחר נכס ואסטרטגיה והרץ. Backtest אינו תחזית.</div></div>${disclaimer('Backtest אינו תחזית. אין look-ahead (החלטה על נתוני היום, ביצוע ב-Open של מחר; דוחות לפי תאריך הגשה). נכס בודד — הטיית שרידות לא נשללת. תוצאות Walk-Forward (OOS) הן ההערכה ההוגנת; in-sample מוצג להשוואה בלבד.')}`;
  const out = main.querySelector('#out');
  const go = async () => {
    const symbol = main.querySelector('#sym').value.trim().toUpperCase(), strategy = main.querySelector('#strat').value, bench = main.querySelector('#bench').value;
    out.innerHTML = loading('טוען נתונים ומריץ…');
    try {
      const [b, bb, macro] = await Promise.all([getBundle(symbol), symbol === bench ? null : getBundle(bench).catch(() => null), api('/macro', { ttl: 600000 }).catch(() => null)]);
      if (!b.prices || b.prices.missing) throw new Error(b.prices?.reason || 'אין מחירים');
      const rf = macro?.DGS3MO?.rows?.length ? macro.DGS3MO.rows.slice(-252).reduce((s, x) => s + x[1], 0) / Math.min(252, macro.DGS3MO.rows.length) / 100 : 0;
      const costs = { commission: +main.querySelector('#comm').value / 100, slippage: +main.querySelector('#slip').value / 100 };
      const from = main.querySelector('#from').value || null, to = main.querySelector('#to').value || null;
      const res = await run('backtest', { rows: b.prices.rows, strategy, costs, start: from, end: to, facts: b.facts && !b.facts.missing ? b.facts : null, profile: { type: b.asset.type, currency: b.asset.currency, sector: b.asset.sector }, rf });
      const r = res.result; if (r.error) throw new Error(r.error);
      let bm = null, bmEq = null;
      if (bb?.prices?.rows){ const bres = await run('backtest', { rows: bb.prices.rows, strategy: 'buyhold', costs, start: r.from, end: r.to, rf }); bm = bres.result.metrics; bmEq = bres.result.equity; }
      const dates = r.equity.map((e) => e[0]); const base = r.equity[0][1];
      const series = [{ name: STRATS[strategy], values: r.equity.map((e) => e[1] / base * 100), color: '#4f8cff', width: 1.8 }, { name: 'Buy & Hold', values: r.buyHold.equity.map((e) => e[1] / r.buyHold.equity[0][1] * 100), color: '#94a3b8' }];
      if (bmEq){ const m = new Map(bmEq.map((e) => e)); const b0 = bmEq[0][1]; series.push({ name: `Benchmark ${bench}`, values: dates.map((d) => (m.has(d) ? m.get(d) / b0 * 100 : null)), color: '#f5a524', dashed: true }); }
      const markers = r.trades.slice(0, 80).flatMap((t) => [{ i: dates.indexOf(t.entryDate), label: '▲', color: '#2fbf71' }, t.exitDate ? { i: dates.indexOf(t.exitDate), label: '▼', color: '#e5484d' } : null].filter(Boolean));
      const wf = res.walkForward;
      out.innerHTML = `<section class="card"><h3>${esc(symbol)} · ${esc(STRATS[strategy])} <span class="muted">${esc(r.from)} → ${esc(r.to)} · מקור מחירים ${esc(b.prices.source)} ${b.facts && !b.facts.missing && strategy === 'signal' ? '· פונדמנטלס point-in-time (' + esc(b.facts.source) + ')' : strategy === 'signal' ? '· ללא פונדמנטלס (טכני+מומנטום+סיכון בלבד)' : ''}</span></h3><div id="eq"></div><div class="muted">עקומת הון (בסיס 100, סקאלה לוגריתמית) · ▲ כניסה ▼ יציאה</div></section>
      <div class="grid g2" style="margin-top:1rem"><section class="card"><h3>מדדים (כל התקופה) ${kind('MODEL')}</h3>${metricsTable(r.metrics, r.buyHold.metrics, bm)}<p class="muted">Rf ל-Sharpe: ${fmt.pct(rf, 2)} (ממוצע DGS3MO/FRED, 0 אם חסר)</p></section>
      <section class="card"><h3>תקופות שוק שונות</h3><table><thead><tr><th>תקופה</th><th class="num">CAGR</th><th class="num">B&H CAGR</th><th class="num">Max DD</th><th class="num">B&H DD</th><th class="num">Sharpe</th><th class="num">טריידים</th></tr></thead><tbody>${res.periods.map((p) => (p.missing ? `<tr><td>${esc(p.label)}</td><td colspan="6" class="muted">אין נתונים לתקופה</td></tr>` : `<tr><td>${esc(p.label)}</td><td class="num ${cls(p.metrics.cagr)}">${fmt.pct(p.metrics.cagr, 1, true)}</td><td class="num ${cls(p.buyHold.cagr)}">${fmt.pct(p.buyHold.cagr, 1, true)}</td><td class="num neg">${fmt.pct(p.metrics.maxDrawdown, 0)}</td><td class="num neg">${fmt.pct(p.buyHold.maxDrawdown, 0)}</td><td class="num">${fmt.num(p.metrics.sharpe)}</td><td class="num">${p.trades}</td></tr>`)).join('')}</tbody></table></section></div>
      ${wf ? (wf.error ? `<div class="empty">${esc(wf.error)}</div>` : `<section class="card" style="margin-top:1rem"><h3>Walk-Forward (IS 3 שנים → OOS שנה) <span class="tag ${wf.stability.label === 'יציב' ? 'fact' : 'stale'}">${esc(wf.stability.label)}</span></h3><div class="grid g2"><div><h4>תוצאת OOS משורשרת (זו ההערכה ההוגנת)</h4>${metricsTable(wf.oosMetrics, null, null)}</div><div><h4>חלונות</h4><table><thead><tr><th>IS</th><th>OOS</th><th>פרמטרים</th><th class="num">Sharpe IS</th><th class="num">Sharpe OOS</th><th class="num">CAGR OOS</th></tr></thead><tbody>${wf.windows.map((w) => `<tr><td class="num">${esc(w.window.isStart.slice(0, 4))}–${esc(w.window.isEnd.slice(0, 4))}</td><td class="num">${esc(w.window.oosStart.slice(0, 7))}→${esc(w.window.oosEnd.slice(0, 7))}</td><td class="num">${esc(JSON.stringify(w.chosen))}</td><td class="num muted">${fmt.num(w.inSample?.sharpe)}</td><td class="num">${fmt.num(w.outOfSample?.sharpe)}</td><td class="num ${cls(w.outOfSample?.cagr)}">${fmt.pct(w.outOfSample?.cagr, 1, true)}</td></tr>`).join('')}</tbody></table></div></div><div id="wfeq"></div><p class="muted">${esc(wf.note)}</p></section>`) : ''}
      <section class="card" style="margin-top:1rem"><h3>טריידים (${r.trades.length})</h3><div class="table-wrap" style="max-height:300px"><table><thead><tr><th>כניסה</th><th class="num">מחיר</th><th>יציאה</th><th class="num">מחיר</th><th class="num">P&L %</th><th class="num">ימים</th><th>סיבה</th></tr></thead><tbody>${r.trades.slice().reverse().map((t) => `<tr><td class="num">${esc(t.entryDate)}</td><td class="num">${fmt.num(t.entryPrice)}</td><td class="num">${esc(t.exitDate || (t.open ? 'פתוח' : ''))}</td><td class="num">${fmt.num(t.exitPrice ?? t.markPrice)}</td><td class="num ${cls(t.pnlPct)}">${fmt.pct(t.pnlPct, 1, true)}</td><td class="num">${t.bars ?? ''}</td><td class="muted">${esc(t.exitReason || t.reason || '')}</td></tr>`).join('')}</tbody></table></div><p class="muted">${esc(r.note)} ${esc(r.survivorshipNote)}</p></section>`;
      out.querySelector('#eq').appendChild(lineChart({ dates, series, height: 320, markers, logScale: true, yFmt: (v) => v.toFixed(0) }));
      if (wf && !wf.error && wf.oosEquity?.length) out.querySelector('#wfeq').appendChild(lineChart({ dates: wf.oosEquity.map((e) => e[0]), height: 200, series: [{ name: 'OOS משורשר', values: wf.oosEquity.map((e) => e[1] / wf.oosEquity[0][1] * 100), color: '#a78bfa', area: true }], yFmt: (v) => v.toFixed(0) }));
    } catch (e) { out.innerHTML = errorBox(e); }
  };
  main.querySelector('#go').onclick = go;
  if (params.symbol) go();
}
