// Paper Trading: תיק וירטואלי + Performance Dashboard מול SPY.
import { api, invalidate } from '../core/api.js';
import { esc, fmt, isNum, cls, toast, modal } from '../core/util.js';
import { sigBadge, kind, loading, errorBox, symLink, kpi } from '../ui/components.js';
import { lineChart } from '../ui/chart.js';

export async function render(main){
  main.innerHTML = loading();
  let p;
  try { p = await api('/paper'); } catch (e) { main.innerHTML = errorBox(e); return; }
  const eq = p.equity || [];
  main.innerHTML = `<div class="page-head"><div><h1>Paper Trading</h1><span class="muted">תיק וירטואלי · ${p.trades} עסקאות · ביצועי המערכת מול SPY</span></div><div class="row"><button class="btn primary" id="buy">＋ קנייה</button></div></div>
  <div class="grid g4" style="margin-bottom:1rem"><div class="card">${kpi('סה"כ שווי (מזומן + ניירות)', fmt.ils(p.totalIls))}</div><div class="card">${kpi('רווח/הפסד מההתחלה', `${fmt.ils(p.pnlIls)} (${fmt.pct(p.pnlPct, 1, true)})`, cls(p.pnlIls))}</div><div class="card">${isNum(p.dayPnlIls) && p.asOf ? kpi(`שינוי בסגירת ${fmt.date(p.asOf)}`, `${fmt.ils(p.dayPnlIls)} (${fmt.pct(p.dayPnlPct, 1, true)})`, cls(p.dayPnlIls)) : kpi('מזומן פנוי / ניירות', `${fmt.ils(p.cashIls)} / ${fmt.ils(p.valueIls)}`)}</div><div class="card">${kpi('ממומש / עמלות / Win rate', `${fmt.ils(p.realizedIls)} / ${fmt.ils(p.commissionsIls)} / ${fmt.pct(p.winRate, 0)}`)}</div></div>
  ${eq.length > 2 ? `<section class="card" style="margin-bottom:1rem"><h3>Performance Dashboard <span class="muted">שווי יומי (נרשם ב-cron) מול SPY, בסיס 100</span></h3><div id="eqc"></div></section>` : '<div class="muted" style="margin-bottom:1rem">עקומת ביצועים תופיע אחרי שיצטברו ימי עיבוד עם פוזיציות פתוחות.</div>'}
  <section class="card"><h3>פוזיציות (מאוחדות לפי נכס)</h3>${p.positions.length ? `<table><thead><tr><th>נכס</th><th class="num">כמות</th><th class="num">מחיר ממוצע</th><th class="num">נוכחי</th><th class="num">עלות ₪</th><th class="num">שווי ₪</th><th class="num">רווח/הפסד ₪</th><th>סיגנל היום</th><th></th></tr></thead><tbody>${p.positions.map((t) => `<tr><td>${symLink(t.symbol, t.name, t.nameHe)}</td><td class="num">${t.qty}</td><td class="num">${fmt.num(t.avgPrice)}</td><td class="num">${fmt.num(t.current)}</td><td class="num">${fmt.ils(t.costIls)}</td><td class="num">${fmt.ils(t.valueIls)}</td><td class="num ${cls(t.pnlIls)}">${fmt.ils(t.pnlIls)} (${fmt.pct(t.pnlPct, 1, true)})</td><td>${t.signal ? sigBadge(t.signal) : '—'}</td><td><button class="btn sm" data-sell="${esc(t.symbol)}" data-qty="${t.qty}" data-px="${t.current || ''}">מכור</button></td></tr>`).join('')}</tbody></table>
  <details style="margin-top:.5rem"><summary class="muted">רישומי קנייה בודדים (${p.open.length})</summary><table><thead><tr><th>נכס</th><th>תאריך</th><th class="num">כמות</th><th class="num">מחיר</th><th class="num">עלות ₪ (כולל עמלה)</th><th>סיגנל בכניסה</th><th>סיבה</th></tr></thead><tbody>${p.open.map((t) => `<tr><td>${symLink(t.symbol)}</td><td class="num">${fmt.dt(t.date)}</td><td class="num">${t.qty}</td><td class="num">${fmt.num(t.price)}</td><td class="num">${fmt.ils(t.costIls)}</td><td>${t.signalAtEntry ? sigBadge(t.signalAtEntry) : '—'}</td><td class="muted" style="white-space:normal">${esc(t.reason || '')}</td></tr>`).join('')}</tbody></table></details>` : '<div class="empty">אין פוזיציות פתוחות</div>'}</section>
  <section class="card" style="margin-top:1rem"><h3>עסקאות סגורות</h3>${p.closed.length ? `<table><thead><tr><th>נכס</th><th>כניסה</th><th class="num">מחיר</th><th>יציאה</th><th class="num">מחיר</th><th class="num">כמות</th><th class="num">P&L</th><th class="num">%</th><th>סיבת יציאה</th></tr></thead><tbody>${p.closed.map((t) => `<tr><td>${symLink(t.symbol)}</td><td class="num">${fmt.date(t.date)}</td><td class="num">${fmt.num(t.price)}</td><td class="num">${fmt.date(t.exitDate)}</td><td class="num">${fmt.num(t.exitPrice)}</td><td class="num">${t.qty}</td><td class="num ${cls(t.pnlIls ?? t.pnl)}">${fmt.ils(t.pnlIls ?? t.pnl)}</td><td class="num ${cls(t.pnlPct)}">${fmt.pct(t.pnlPct, 1, true)}</td><td class="muted">${esc(t.exitReason || '')}</td></tr>`).join('')}</tbody></table>` : '<div class="empty">אין עסקאות סגורות</div>'}</section>`;
  if (eq.length > 2){ const b0 = eq[0][1] || 1, s0 = eq.find((e) => isNum(e[2]))?.[2] || 1; main.querySelector('#eqc').appendChild(lineChart({ dates: eq.map((e) => e[0]), height: 220, series: [{ name: 'חשבון וירטואלי (₪)', values: eq.map((e) => (b0 ? e[1] / b0 * 100 : null)), color: '#4f8cff' }, { name: 'SPY', values: eq.map((e) => (isNum(e[2]) ? e[2] / s0 * 100 : null)), color: '#f5a524', dashed: true }], yFmt: (v) => v.toFixed(0) })); }
  const order = (symbol, side, qty, price) => { const mm = modal(`<h2>${side === 'buy' ? 'קנייה' : 'מכירה'} וירטואלית</h2><div class="stack"><label>סימבול <input id="s" value="${esc(symbol || '')}"></label><label>כמות <input id="q" type="number" value="${qty || 10}" step="1"></label><label>מחיר (ריק = quote/סגירה אחרונה) <input id="px" type="number" step="0.01" value="${price || ''}"></label><label>סיבה <input id="r"></label><div class="row"><button class="btn primary" id="ok">בצע</button><button class="btn" data-close>ביטול</button></div></div>`); mm.el.querySelector('#ok').onclick = async () => { try { const body = { symbol: mm.el.querySelector('#s').value.trim().toUpperCase(), side, qty: +mm.el.querySelector('#q').value, reason: mm.el.querySelector('#r').value }; const px = +mm.el.querySelector('#px').value; if (px) body.price = px; const r = await api('/paper/order', { method: 'POST', body }); invalidate('/paper'); toast(`בוצע במחיר ${r.price} (${r.priceSource?.source || ''})`); mm.close(); render(main); } catch (e) { toast(e.message, 'err'); } }; };
  main.querySelector('#buy').onclick = () => order('', 'buy');
  main.addEventListener('click', (e) => { const b = e.target.closest('[data-sell]'); if (b) order(b.dataset.sell, 'sell', +b.dataset.qty, b.dataset.px); });
}
