// Market Regime: כללים גלויים, קלטים, Fear&Greed מקומי, גרפי מאקרו, היסטוריה.
import { api } from '../core/api.js';
import { esc, fmt, isNum, cls } from '../core/util.js';
import { kind, loading, errorBox, kpi } from '../ui/components.js';
import { lineChart } from '../ui/chart.js';

export async function render(main){
  main.innerHTML = loading();
  let r, macro, hist;
  try { [r, macro, hist] = await Promise.all([api('/regime', { ttl: 60000 }), api('/macro', { ttl: 300000 }), api('/regime/history', { ttl: 300000 })]); } catch (e) { main.innerHTML = errorBox(e); return; }
  const inp = r.inputs || {};
  const ix = (k, lbl) => (inp[k] ? kpi(lbl, `${fmt.num(inp[k].price, 0)} <small class="${inp[k].aboveSma200 ? 'pos' : 'neg'}">${inp[k].aboveSma200 ? 'מעל' : 'מתחת'} SMA200</small>`) : kpi(lbl, '<span class="tag missing">Missing</span>'));
  main.innerHTML = `<div class="page-head"><div><h1>Market Regime</h1><span class="muted">${esc(r.date || '')} · ${kind('MODEL')} · ${esc(r.method || '')}</span></div><div class="row"><span class="tag ${r.risk === 'Risk On' ? 'fact' : r.risk === 'Risk Off' ? 'missing' : ''}" style="font-size:1rem">${esc(r.risk)}</span><span class="tag ${r.trend === 'Bull Trend' ? 'fact' : r.trend === 'Bear Trend' ? 'missing' : 'stale'}" style="font-size:1rem">${esc(r.trend)}</span></div></div>
  <div class="grid g4" style="margin-bottom:1rem">${ix('spx', 'S&P 500')}${ix('ndq', 'Nasdaq')}${ix('rut', 'Russell 2000')}${ix('ta35', 'ת"א 35')}${kpi('VIX', fmt.num(inp.vix, 1), inp.vix > 30 ? 'neg' : inp.vix < 20 ? 'pos' : 'warn')}${kpi('תשואה 10y / 2y', `${fmt.num(inp.dgs10, 2)}% / ${fmt.num(inp.dgs2, 2)}%`)}${kpi('עקום 10−2', fmt.num(inp.curve, 2), cls(inp.curve))}${kpi('ריבית הפד', isNum(inp.fedFunds) ? fmt.num(inp.fedFunds, 2) + '%' : '—')}${kpi('אינפלציה (CPI YoY)', fmt.pct(inp.inflation, 1))}${kpi('מרווח HY', isNum(inp.hy) ? fmt.num(inp.hy, 2) + '%' : '—')}${kpi('USD/ILS (3M)', `${fmt.num(inp.usdils, 3)} <small class="${cls(inp.usdilsChange3m)}">${fmt.pct(inp.usdilsChange3m, 1, true)}</small>`)}${kpi('נפט WTI', fmt.num(inp.oil, 1))}</div>
  <div class="grid g-2-1"><section class="card"><h3>הכללים (כולם גלויים)</h3><table><thead><tr><th>כלל</th><th class="num">ערך</th><th class="num">סף</th><th>כיוון</th><th>מצב</th></tr></thead><tbody>${r.rules.map((x) => `<tr><td>${esc(x.desc)}</td><td class="num">${isNum(x.value) ? fmt.num(x.value, 3) : '—'}</td><td class="num">${isNum(x.threshold) ? fmt.num(x.threshold, 3) : '—'}</td><td><span class="tag">${esc(x.dir)}</span></td><td>${x.passed === null ? '<span class="tag missing">אין נתון</span>' : x.passed ? '<span class="tag fact">מתקיים</span>' : '<span class="muted">לא</span>'}</td></tr>`).join('')}</tbody></table><p class="muted">Trend: SPX מעל SMA200 + SMA50>SMA200 + DD<10% = Bull; DD>20% = Bear; אחרת Correction. Risk: יחס כללי risk-on מתקיימים פחות risk-off (riskScore=${r.riskScore}).</p></section>
  <section class="card"><h3>Fear & Greed (מקומי)</h3>${r.fearGreed ? `<div class="kpi"><span class="v">${r.fearGreed.value}</span><span class="l">${esc(r.fearGreed.label)}</span></div><div class="progress" style="margin:.5rem 0"><i style="width:${r.fearGreed.value}%"></i></div><table><tbody>${r.fearGreed.components.map((c) => `<tr><td>${esc(c.desc)}</td><td class="num">${c.value}</td><td class="num muted">×${c.weight}</td></tr>`).join('')}</tbody></table>` : '<div class="empty">אין נתונים</div>'}${r.missingInputs?.length ? `<p class="muted">קלטים חסרים: ${esc(r.missingInputs.join(', '))}</p>` : ''}<h4 style="margin-top:.8rem">מקורות</h4><div class="row">${Object.entries(r.dataAsOf || {}).map(([k, v]) => `<span class="tag ${v.stale ? 'stale' : ''}">${esc(k)}: ${esc(v.source)} ${esc(v.asOf)}</span>`).join('')}</div></section></div>
  <div class="grid g2" style="margin-top:1rem" id="charts"></div>
  ${hist?.length > 1 ? `<section class="card" style="margin-top:1rem"><h3>היסטוריית סיווג (append-only)</h3><table><thead><tr><th>תאריך</th><th>Risk</th><th>Trend</th><th class="num">F&G</th><th class="num">VIX</th></tr></thead><tbody>${hist.slice().reverse().slice(0, 30).map((h) => `<tr><td class="num">${esc(h.date)}</td><td>${esc(h.risk)}</td><td>${esc(h.trend)}</td><td class="num">${h.fearGreed ?? '—'}</td><td class="num">${fmt.num(h.vix, 1)}</td></tr>`).join('')}</tbody></table></section>` : ''}`;
  const charts = main.querySelector('#charts');
  const series = [['VIXCLS', 'VIX'], ['DGS10', 'תשואת 10 שנים'], ['T10Y2Y', 'עקום 10−2'], ['BAMLH0A0HYM2', 'מרווח HY'], ['USDILS', 'USD/ILS'], ['CPIAUCSL', 'CPI']];
  for (const [id, label] of series){ const m = macro[id]; if (!m?.rows?.length) continue; const rows = m.rows.slice(-750); const c = document.createElement('section'); c.className = 'card'; c.innerHTML = `<h3>${esc(label)} <span class="muted">${esc(m.source)} · ${esc(m.asOf)}</span></h3>`; c.appendChild(lineChart({ dates: rows.map((x) => x[0]), height: 160, series: [{ name: label, values: rows.map((x) => x[1]), area: true }] })); charts.appendChild(c); }
}
