// הגדרות: חיבור ל-API, טוקן, משקלי הציון, גודל תיק, ערוצי התראה, מצב חישוב, תפעול (cron/עיבוד בדפדפן).
import { api, invalidate, health, getBundle } from '../core/api.js';
import { run } from '../core/compute.js';
import { settings, idb } from '../core/store.js';
import { esc, fmt, toast, COMP_HE } from '../core/util.js';
import { loading, errorBox } from '../ui/components.js';

export async function render(main, params = {}){
  if (params.token){ settings.set({ token: params.token }); invalidate(''); toast('הטוקן נשמר — האפליקציה מחוברת'); location.hash = '#/settings'; return; }
  const s = settings.get();
  main.innerHTML = loading();
  let srv = null, h = null, keys = null; try { [srv, h, keys] = await Promise.all([api('/settings').catch(() => null), health(), api('/keys', { auth: true }).catch(() => null)]); } catch {}
  const weights = srv?.weights || { fundamental: 12, valuation: 15, growth: 12, quality: 10, technical: 12, momentum: 10, analyst: 8, sentiment: 6, macro: 7, risk: 8 };
  main.innerHTML = `<div class="page-head"><h1>הגדרות</h1></div><div class="grid g2">
  <section class="card"><h3>חיבור</h3><div class="stack"><label>כתובת ה-API (Worker) <input id="apiUrl" value="${esc(s.apiUrl)}"></label><label>טוקן כתיבה (APP_TOKEN של ה-Worker) <input id="token" type="password" value="${esc(s.token)}"></label><label>מצב חישוב <select id="mode"><option value="auto" ${s.computeMode === 'auto' ? 'selected' : ''}>אוטומטי (שרת, ונפילה לדפדפן)</option><option value="server" ${s.computeMode === 'server' ? 'selected' : ''}>שרת בלבד</option><option value="browser" ${s.computeMode === 'browser' ? 'selected' : ''}>דפדפן</option></select></label><div class="row"><button class="btn primary" id="saveLocal">שמור</button><button class="btn" id="clearCache">נקה מטמון מקומי</button></div></div>
  <h4 style="margin-top:.8rem">מצב השרת</h4>${h?.ok ? `<div class="row"><span class="tag fact">מחובר · v${esc(h.version)}</span><span class="tag ${h.auth === 'token' ? 'fact' : 'missing'}">auth: ${esc(h.auth)}</span><span class="tag ${h.kv === 'bound' ? 'fact' : 'missing'}">KV: ${esc(h.kv)}</span><span class="tag">AI: ${esc(h.ai)}</span><span class="tag ${h.alerts?.telegram ? 'fact' : ''}">Telegram ${h.alerts?.telegram ? '✔' : '✖'}</span><span class="tag ${h.alerts?.email ? 'fact' : ''}">Email ${h.alerts?.email ? '✔' : '✖'}</span></div><table style="margin-top:.5rem"><thead><tr><th>ספק</th><th>מפתח</th><th>יכולות</th><th class="num">תקציב היום</th></tr></thead><tbody>${h.providers.map((p) => `<tr><td>${esc(p.id)}</td><td>${p.available ? '<span class="tag fact">' + esc(p.key) + '</span>' : '<span class="tag missing">חסר</span>'}</td><td class="muted">${esc(p.supports.join(', '))}</td><td class="num">${h.budget?.[p.id] ? `${h.budget[p.id].used}/${h.budget[p.id].limit}` : '—'}</td></tr>`).join('')}</tbody></table><p class="muted">מפתחות מוזנים ב-Cloudflare → Workers → invest-api → Settings → Variables (Secrets): FINNHUB_KEY, FMP_KEY, ALPHAVANTAGE_KEY, FRED_KEY, EODHD_KEY, APP_TOKEN, TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID, RESEND_KEY, ALERT_EMAIL, ANTHROPIC_API_KEY.</p>${h.recentErrors?.length ? `<details><summary class="muted">שגיאות אחרונות (${h.recentErrors.length})</summary><ul class="list muted" style="font-size:.75rem">${h.recentErrors.map((e) => `<li>${esc(e.ts.slice(5, 16))} ${esc(e.where)}: ${esc(e.msg)}</li>`).join('')}</ul></details>` : ''}` : `<div class="empty">אין חיבור: ${esc(h?.error || '')}</div>`}</section>
  <section class="card"><h3>מודל הציון — משקלים</h3><p class="muted">סכום המשקלים מנורמל אוטומטית. כל שינוי יוצר גרסת משקלים חדשה (snapshots ישנים לא משתנים).</p><div class="grid g2" id="w">${Object.entries(weights).map(([k, v]) => `<label>${esc(COMP_HE[k] || k)} <input type="number" min="0" max="50" data-w="${k}" value="${v}"></label>`).join('')}</div>
  <h4 style="margin-top:.8rem">תיק והתראות</h4><div class="stack"><label>גודל תיק (₪) <input id="size" type="number" value="${srv?.portfolioSize || s.portfolioSize}"></label><div class="row">ערוצי התראה ברירת מחדל: ${['browser', 'telegram', 'email'].map((c) => `<label><input type="checkbox" data-ch="${c}" ${(srv?.alertChannels || ['browser']).includes(c) ? 'checked' : ''}> ${c}</label>`).join('')}</div><div class="row"><label><input type="checkbox" id="dSig" ${srv?.alertDefaults?.signalChange !== false ? 'checked' : ''}> שינוי סיגנל ברשימת המעקב</label><label><input type="checkbox" id="dNews" ${srv?.alertDefaults?.materialNews !== false ? 'checked' : ''}> חדשות מהותיות ברשימת המעקב</label></div><button class="btn primary" id="saveSrv">שמור בשרת</button></div></section>
  <section class="card span2"><h3>מפתחות ספקי נתונים</h3><p class="muted">המפתחות נשמרים בשרת (KV של ה-Worker) ולעולם לא חוזרים לדפדפן. בלי מפתחות עובדים Stooq (מחירים), SEC EDGAR (דוחות) ובנק ישראל (שער). מפתח חינמי לוקח דקה: <a href="https://finnhub.io/register" target="_blank" rel="noopener">Finnhub</a> · <a href="https://fredaccount.stlouisfed.org/apikeys" target="_blank" rel="noopener">FRED</a> · <a href="https://www.alphavantage.co/support/#api-key" target="_blank" rel="noopener">Alpha Vantage</a> · <a href="https://site.financialmodelingprep.com/developer/docs" target="_blank" rel="noopener">FMP</a>.</p>
  ${keys ? `<div class="grid g2">${keys.map((k) => `<label>${esc(k.label)} ${k.set ? `<span class="tag fact">מוגדר${k.source === 'secret' ? ' (secret)' : ''} ${esc(k.masked)}</span>` : '<span class="tag">לא מוגדר</span>'}<div class="row"><input data-key="${k.name}" placeholder="${k.set ? 'הדבק ערך חדש להחלפה' : 'הדבק מפתח'}" style="flex:1" ${k.source === 'secret' ? 'disabled title="מוגדר כ-Secret ב-Cloudflare"' : ''}><button class="btn sm" data-savekey="${k.name}">שמור</button></div></label>`).join('')}</div>` : '<div class="empty">נדרש טוקן כתיבה תקין כדי לנהל מפתחות</div>'}</section>
  <section class="card span2"><h3>תפעול — עיבוד יומי</h3><p class="muted">ה-cron ב-Cloudflare מעבד את ה-universe באצ'ים (CRON_BATCH נכסים כל 2 דקות). בתוכנית Workers החינמית (10ms CPU לקריאה) העיבוד בשרת עלול להיכשל — אז מריצים כאן "עיבוד בדפדפן": אותו engine בדיוק, התוצאות נשמרות ב-DB (append-only) כמו מה-cron.</p><div class="row"><button class="btn" id="cronRun">הרץ עיבוד בשרת עכשיו (5 נכסים לכל לחיצה)</button><button class="btn primary" id="localRun">עיבוד יומי בדפדפן ושמירה</button><span id="prog" class="muted"></span></div><div id="cronStatus" class="muted" style="margin-top:.5rem"></div></section></div>`;
  main.querySelectorAll('[data-savekey]').forEach((b) => b.onclick = async () => { const inp = main.querySelector(`[data-key="${b.dataset.savekey}"]`); try { await api('/keys', { method: 'POST', body: { name: b.dataset.savekey, value: inp.value.trim() } }); invalidate(''); toast('נשמר בשרת'); render(main); } catch (e) { toast(e.message, 'err'); } });
  main.querySelector('#saveLocal').onclick = () => { settings.set({ apiUrl: main.querySelector('#apiUrl').value.trim(), token: main.querySelector('#token').value.trim(), computeMode: main.querySelector('#mode').value }); invalidate(''); toast('נשמר מקומית'); render(main); };
  main.querySelector('#clearCache').onclick = async () => { await idb.clear(); invalidate(''); toast('המטמון נוקה'); };
  main.querySelector('#saveSrv').onclick = async () => { try { const w = {}; main.querySelectorAll('[data-w]').forEach((i) => { w[i.dataset.w] = +i.value; }); const r = await api('/settings', { method: 'POST', body: { weights: w, portfolioSize: +main.querySelector('#size').value, alertChannels: [...main.querySelectorAll('[data-ch]:checked')].map((c) => c.dataset.ch), alertDefaults: { signalChange: main.querySelector('#dSig').checked, materialNews: main.querySelector('#dNews').checked } } }); settings.set({ portfolioSize: r.portfolioSize }); invalidate(''); toast('נשמר בשרת — ייכנס לתוקף בעיבוד הבא'); } catch (e) { toast(e.message, 'err'); } };
  const status = async () => { try { const c = await api('/cron/status'); main.querySelector('#cronStatus').textContent = c.state?.day ? `יום ${c.state.day}: הושלמו ${c.state.done?.length ?? c.state.done ?? 0}, בתור ${c.state.queueLeft ?? 0}, שגיאות ${c.state.errors?.length ?? 0}, ${c.state.finalized ? 'הסתיים' : 'בתהליך'} · ריצה אחרונה ${fmt.dt(c.last?.at)}: ${(c.last?.log || []).join(' | ')}` : 'טרם רץ'; } catch {} };
  status();
  main.querySelector('#cronRun').onclick = async () => { try { const r = await api('/cron/run?batch=5&force=1', { method: 'POST' }); toast(`עובדו ${r.processed}, נותרו ${r.queueLeft}${r.finalized ? ' — הסתיים' : ''}`); status(); } catch (e) { toast(e.message, 'err'); } };
  main.querySelector('#localRun').onclick = async () => {
    const prog = main.querySelector('#prog');
    try {
      const [u, w, regime, macro] = await Promise.all([api('/universe'), api('/watchlist'), api('/regime'), api('/macro')]);
      const syms = [...new Set([...u.items.map((a) => a.symbol), ...w.items.map((x) => x.symbol)])];
      const bundles = [];
      for (let i = 0; i < syms.length; i++){ prog.textContent = `טוען ${i + 1}/${syms.length}`; try { const b = await getBundle(syms[i], { maxAgeH: 6 }); if (b.prices && !b.prices.missing) bundles.push({ ...b, asset: { ...(u.items.find((a) => a.symbol === syms[i]) || {}), ...b.asset } }); } catch {} }
      const spy = bundles.find((b) => b.asset.symbol === 'SPY')?.prices?.rows, qqq = bundles.find((b) => b.asset.symbol === 'QQQ')?.prices?.rows;
      const res = await run('analyzeAll', { bundles, regime, benchRows: spy, techRows: qqq, dgs10Rows: macro?.DGS10?.rows, weights: srv?.weights, sizeIls: srv?.portfolioSize, usdils: macro?.USDILS?.rate }, (p) => { prog.textContent = `מחשב ${Math.round(p * 100)}%`; });
      prog.textContent = 'שומר…';
      const r = await api('/snapshots', { method: 'POST', body: { date: new Date().toISOString().slice(0, 10), snapshots: res.snaps, rank: res.rank, reco: res.reco, regime } });
      prog.textContent = ''; invalidate(''); toast(`נשמרו ${r.written}/${r.received} snapshots ליום ${r.day}${r.alerts ? `, ${r.alerts} התראות` : ''}`);
    } catch (e) { prog.textContent = ''; toast(e.message, 'err'); }
  };
}
