import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { shouldSkipChange, roundState, marker, parseMarkers, claudeSignals, kindOf, parseFrontMatter, findPolicies, matchPolicies, buildDiff, buildMessages, normalize, formatComment, redact, LABELS, LIMITS, FINDING_TYPES } from './review.mjs';

const f = (filename, additions = 5, deletions = 1, patch = '@@ -1 +1 @@\n-a\n+b') => ({ filename, additions, deletions, changes: additions + deletions, status: 'modified', patch });
const gpt = (sha, round, verdict, at) => ({ id: round, created_at: at, user: { login: 'github-actions[bot]' }, body: `## GPT REVIEW: ${verdict}\n${marker({ sha, round, verdict })}\nממצא` });

test('gpt-review: דילוג על שינויים לא מהותיים — ops, תווית, draft, רק קבצים שלא נסקרים', () => {
  assert.equal(shouldSkipChange({ files: [f('english/js/app.js')], title: 'תיקון' }), null);
  assert.match(shouldSkipChange({ files: [f('.github/invest-ops/command')], title: 'ops: dump' }), /ops:/);
  assert.match(shouldSkipChange({ files: [f('.github/invest-ops/command'), f('english/icon.png')], title: 'x' }), /אינם נסקרים/);
  assert.match(shouldSkipChange({ files: [f('a.js', 0, 0)], title: 'x' }), /אין שינוי/);
  assert.match(shouldSkipChange({ files: [f('a.js')], title: 'x', labels: [LABELS.SKIP] }), /skip-gpt-review/);
  assert.match(shouldSkipChange({ files: [f('a.js')], title: 'x', draft: true }), /draft/);
});

test('gpt-review: ספירת סבבים, דדופליקציה לפי SHA, סבב אחרון אחרי MAX חוסמים, והמתנה להכרעת בעל הריפו', () => {
  const none = roundState([{ body: 'סתם תגובה' }], 'abc1234', 3);
  assert.deepEqual([none.round, none.alreadyReviewed, none.finalRound, none.blockedRounds], [1, false, false, 0]);
  const cs = [gpt('aaaaaaa', 1, 'BLOCKED', '1'), { body: 'תשובה' }, gpt('bbbbbbb', 2, 'BLOCKED', '2')];
  const s = roundState(cs, 'bbbbbbb1234', 3);
  assert.equal(s.alreadyReviewed, true, 'אותו head כבר נסקר'); assert.equal(s.round, 3); assert.equal(s.finalRound, false);
  const s2 = roundState([...cs, gpt('ccccccc', 3, 'BLOCKED', '3')], 'ddddddd', 3);
  assert.equal(s2.finalRound, true, 'אחרי 3 חוסמים — הסבב הבא הוא האחרון'); assert.equal(s2.round, 4);
  const s3 = roundState([...cs, gpt('ccccccc', 3, 'OWNER_DECISION_REQUIRED', '3')], 'eeeeeee', 3);
  assert.equal(s3.ownerDecided, true);
  assert.equal(roundState([gpt('aaaaaaa', 1, 'PASS', '1')], 'fffffff', 3).blockedRounds, 0, 'PASS לא נספר כסבב חוסם');
  assert.equal(parseMarkers([{ body: 'x' }]).length, 0);
});

test('gpt-review: זיהוי Claude לפי כמה אותות, וסיווג תגובות', () => {
  assert.deepEqual(claudeSignals({ branch: 'main', commits: [], body: '' }), []);
  const s = claudeSignals({ branch: 'claude/x-1', commits: [{ commit: { message: 'fix\n\nCo-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>\nClaude-Session: https://claude.ai/code/s' } }], body: '🤖 Generated with [Claude Code](https://claude.com/claude-code)' });
  assert.equal(s.length, 4, s.join(','));
  assert.deepEqual(claudeSignals({ branch: 'ccr-abc-def' }), ['ענף ccr-*']);
  assert.equal(kindOf({ body: marker({ sha: 'a', round: 1, verdict: 'PASS' }), user: { login: 'github-actions[bot]' } }), 'GPT');
  assert.equal(kindOf({ body: 'תוקן\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_', user: { login: 'meirco199-prog' } }), 'Claude');
  assert.equal(kindOf({ body: 'הערה', user: { login: 'meirco199-prog' } }), 'בעל הריפו (meirco199-prog)');
  assert.equal(kindOf({ body: 'x', user: { login: 'other[bot]' } }), 'bot');
});

test('gpt-review: מדיניות .ai/REVIEW.md — front-matter, התאמה לפי תיקייה ו-applies_to, השורש תמיד', () => {
  const { meta, body } = parseFrontMatter('---\napplies_to: [english-ai/, english-live/]\ntest: node --test x\ndocs: [a.md]\n---\n# כללים\n- אין fake metrics');
  assert.deepEqual(meta.applies_to, ['english-ai/', 'english-live/']); assert.equal(meta.test, 'node --test x'); assert.deepEqual(meta.docs, ['a.md']); assert.match(body, /^# כללים/);
  assert.deepEqual(parseFrontMatter('# בלי front matter').meta, {});
  const root = mkdtempSync(join(tmpdir(), 'gr-'));
  for (const d of ['.ai', 'english/.ai', 'food/.ai']) mkdirSync(join(root, d), { recursive: true });
  writeFileSync(join(root, '.ai/REVIEW.md'), '# כללי');
  writeFileSync(join(root, 'english/.ai/REVIEW.md'), '---\napplies_to: [english-ai/]\n---\n# אנגלית');
  writeFileSync(join(root, 'food/.ai/REVIEW.md'), '# אוכל');
  const all = findPolicies(root);
  assert.deepEqual(all.map((p) => p.dir), ['', 'english/', 'food/']);
  assert.deepEqual(matchPolicies(all, [f('english-ai/worker.js')]).map((p) => p.dir), ['', 'english/'], 'applies_to תופס');
  assert.deepEqual(matchPolicies(all, [f('remi/x.js')]).map((p) => p.dir), [''], 'בלי מדיניות פרויקט — רק הכללי');
  assert.deepEqual(matchPolicies(all, [f('food/index.html'), f('english/js/a.js')]).map((p) => p.dir), ['', 'english/', 'food/']);
});

test('gpt-review: ה-diff בתקציב — קוד קודם, קבצי דילוג בחוץ, שורות ענק וקבצים גדולים מקוצרים, העודף רק ברשימה', () => {
  const files = [f('README.md', 1, 0), f('english/js/app.js', 3, 3, 'x'.repeat(2000)), f('english/icon.png', 0, 0, null), f('invest-api/worker.js', 500, 100, ('y'.repeat(100) + '\n').repeat(300))];
  const d = buildDiff(files, { ...LIMITS, diffChars: 10000, fileChars: 14000 });
  assert.ok(d.text.indexOf('english/js/app.js') < d.text.indexOf('README.md'), 'קוד לפני md');
  assert.ok(!d.text.includes('icon.png')); assert.ok(d.list.includes('icon.png (modified, +0 −0) — לא נסקר'));
  assert.ok(d.text.includes('(שורה קוצרה)'));
  assert.ok(d.omitted.length === 1 && d.omitted[0].startsWith('invest-api/worker.js'), 'הקובץ הגדול מחוץ לתקציב');
  assert.ok(d.chars <= 10000);
});

test('gpt-review: ההודעות למודל כוללות סיווג, שערי אישור, מדיניות, Issue, CI, בדיקות, סבבים ותשובות', () => {
  const ctx = { kind: 'pr', repo: 'o/r', number: 7, title: 'T', body: 'B', headSha: 'abcdef1', branch: 'claude/x', baseRef: 'main', issues: [{ number: 3, title: 'הדרישה', body: 'רוצה X' }], diff: 'DIFF', files: '- a.js', ci: [{ name: 'invest-api tests', status: 'completed', conclusion: 'success' }], tests: [{ cmd: 'node --test', code: 0, out: 'ok 12' }], docs: [{ path: 'english/README.md', text: 'README' }], policies: [{ path: 'english/.ai/REVIEW.md', body: 'אין fake metrics' }], previous: [{ round: 1, verdict: 'BLOCKED', created_at: '2026-09-29T10:00:00Z', body: 'ממצא ישן' }], replies: [{ created_at: '2026-09-29T11:00:00Z', user: { login: 'meirco199-prog' }, body: 'תוקן\n\n_Generated by [Claude Code](x)_' }], signals: ['ענף claude/*'], round: 2, maxRounds: 3, finalRound: false };
  const [sys, usr] = buildMessages(ctx);
  for (const t of FINDING_TYPES) assert.ok(sys.content.includes(`- ${t}`), t);
  assert.ok(sys.content.includes('כסף אמיתי') && sys.content.includes('סבב 2 מתוך 3'));
  for (const s of ['#3: הדרישה', 'אין fake metrics', 'invest-api tests: completed / success', 'node --test → exit 0', 'README', 'סבב 1 (BLOCKED', '· Claude\nתוקן', 'DIFF', 'ענף claude/*']) assert.ok(usr.content.includes(s), s);
  const [sysFinal] = buildMessages({ ...ctx, finalRound: true });
  assert.ok(sysFinal.content.includes('הסבב האחרון') && sysFinal.content.includes('dispute'));
});

test('gpt-review: אכיפת הפסיקה — SECURITY תמיד חוסם, OPTIONAL לעולם לא, BLOCKED בסבב אחרון → OWNER_DECISION_REQUIRED', () => {
  const r = normalize({ verdict: 'PASS', summary: 's', findings: [{ type: 'SECURITY', blocking: false, title: 'מפתח בלקוח' }, { type: 'OPTIONAL IMPROVEMENT', blocking: true, title: 'שם' }] });
  assert.equal(r.verdict, 'BLOCKED'); assert.deepEqual(r.findings.map((x) => x.blocking), [true, false]);
  assert.equal(normalize({ verdict: 'BLOCKED', summary: 's', findings: [{ type: 'TEST GAP', blocking: false, title: 'x' }] }).verdict, 'PASS', 'ממצא לא חוסם = PASS');
  const fin = normalize({ verdict: 'BLOCKED', summary: 's', findings: [{ type: 'BUG', blocking: true, title: 'באג' }], dispute: { claude_view: 'c', gpt_view: 'g', options: [{ option: 'א', consequence: 'ב' }] } }, { finalRound: true });
  assert.equal(fin.verdict, 'OWNER_DECISION_REQUIRED'); assert.equal(fin.dispute.claude_view, 'c');
  assert.equal(normalize({ verdict: 'PASS', summary: 's', findings: [] }, { finalRound: true }).verdict, 'PASS', 'בסבב אחרון תיקון מלא = PASS');
  assert.equal(normalize({ findings: [{ type: 'לא קיים', blocking: true, title: 'x' }] }).findings[0].type, 'BUG');
});

test('gpt-review: התגובה — כותרת GPT REVIEW, סמן, ממצאים חוסמים קודם, שערי אישור, מחלוקת למאיר, הסתרת סודות', () => {
  const ctx = { kind: 'pr', number: 7, headSha: 'abcdef1234', round: 2, maxRounds: 3, model: 'gpt-5', runUrl: 'https://x/run/1', usage: { prompt_tokens: 100, completion_tokens: 20 }, signals: ['ענף claude/*'] };
  const blocked = normalize({ verdict: 'BLOCKED', summary: 'סיכום', checked: ['a'], tests_checked: ['t'], findings: [{ type: 'TEST GAP', blocking: false, title: 'חסר טסט', file: 'a.js', line: null, problem: 'p', why: 'w', reproduce: null, fix: 'f' }, { type: 'BUG', blocking: true, title: 'באג', file: 'a.js', line: 12, problem: 'p sk-abcdefghijklmnop1234', why: 'w', reproduce: 'r', fix: 'f' }], owner_gates: ['שימוש בכסף אמיתי'], notes: ['n'] });
  const b = formatComment(blocked, ctx);
  assert.ok(b.startsWith('## GPT REVIEW: BLOCKED ❌ (סבב 2/3)')); assert.ok(b.includes(marker({ sha: 'abcdef1234', round: 2, verdict: 'BLOCKED' })));
  assert.ok(b.indexOf('[BUG] באג') < b.indexOf('[TEST GAP]'), 'חוסם קודם'); assert.ok(b.includes('`a.js:12` 🔴 חוסם'));
  assert.ok(b.includes('OWNER_APPROVAL_REQUIRED') && b.includes('כסף אמיתי')); assert.ok(b.includes('מפעילה סבב 3/3'));
  const last = formatComment(blocked, { ...ctx, round: 3 }); assert.ok(last.includes('(סבב 3/3)') && last.includes('סבב ההכרעה'));
  assert.ok(formatComment(blocked, { ...ctx, round: 4 }).includes('סבב הכרעה אחרי 3 סבבים'));
  assert.ok(!b.includes('sk-abcdefghijklmnop1234') && b.includes('[REDACTED]')); assert.ok(b.includes('tokens in/out: 100/20'));
  const pass = formatComment(normalize({ verdict: 'PASS', summary: 'טוב', checked: ['x'], tests_checked: ['12/12'], findings: [], notes: ['הערה'] }), ctx);
  assert.ok(pass.startsWith('## GPT REVIEW: PASS ✅') && pass.includes('אין ממצאים מהותיים') && pass.includes('אפשר למזג') && pass.includes('- הערה'));
  const own = formatComment(normalize({ verdict: 'BLOCKED', summary: 's', findings: [{ type: 'BUG', blocking: true, title: 'b', problem: 'p', why: 'w', fix: 'f' }], dispute: { claude_view: 'C', gpt_view: 'G', options: [{ option: 'לקבל את Claude', consequence: 'X' }] } }, { finalRound: true }), ctx);
  assert.ok(own.includes('OWNER_DECISION_REQUIRED ⚖️') && own.includes('@meirco199-prog') && own.includes('**מה Claude חושב:** C') && own.includes('לקבל את Claude → X'));
  assert.equal(redact('ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZ012345 github_pat_ABCDEFGHIJKLMNOPQRSTUVWXYZ'), '[REDACTED] [REDACTED]');
});
